add kubernetes deployment management
labex-labs/scenarios pull request #112
Opened 2023-03-02 06:41 UTC by joker-bai

# PR Checklist

Please post the link to the PR-related issue here (请将 PR 相关的 issues 的链接贴于此处):

Please make sure you've completed the relevant tasks for this PR from the following list (请确保完成下方检查项，提交后打勾):

- [x] The structure of the lab/challenge is correct.(实验/挑战的结构正确)
- [x] The format of the lab/challenge is correct.(实验/挑战的格式正确)
- [x] The code and verification scripts have been tested in the environment.(代码和验证脚本在环境中测试通过)
- [x] I promise that I have not plagiarised and have not copied the solution from other sources, AIGC is not included.(我保证没有抄袭，也没有从其他来源复制解决方案，AIGC 不包括在内)

See the [Contribution Guidelines](https://labex-docs.vercel.app/) for more details.(请参阅 [贡献指南](https://labex-docs.vercel.app/) 了解更多信息。)

2023-04-03 07:34 UTC, huhuhang requested changes

2023-04-03 07:34 UTC, huhuhang commented on kubernetes/challenge-kubernetes-deployment-management/step1.md
> +   - Use the `baidjay/hello-world:v2.0` image.
这个镜像需要放到我们的账号下面，避免未来失效。

2023-04-03 07:34 UTC, huhuhang commented on kubernetes/challenge-kubernetes-deployment-management/step1.md
> +   - Use the `baidjay/hello-world:v2.0` image.
账号密码已发。

2023-04-06 03:02 UTC, joker-bai commented
已提交

2023-04-07 07:03 UTC, huhuhang approved these changes

2023-04-07 07:03 UTC, merged

2023-04-17 04:47 UTC, huhuhang commented
Hi, @joker-bai 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。