add kubernetes advance scheduler
labex-labs/scenarios pull request #113
Opened 2023-03-02 06:51 UTC by joker-bai

# PR Checklist

Please post the link to the PR-related issue here (请将 PR 相关的 issues 的链接贴于此处):

Please make sure you've completed the relevant tasks for this PR from the following list (请确保完成下方检查项，提交后打勾):

- [x] The structure of the lab/challenge is correct.(实验/挑战的结构正确)
- [x] The format of the lab/challenge is correct.(实验/挑战的格式正确)
- [x] The code and verification scripts have been tested in the environment.(代码和验证脚本在环境中测试通过)
- [x] I promise that I have not plagiarised and have not copied the solution from other sources, AIGC is not included.(我保证没有抄袭，也没有从其他来源复制解决方案，AIGC 不包括在内)

See the [Contribution Guidelines](https://labex-docs.vercel.app/) for more details.(请参阅 [贡献指南](https://labex-docs.vercel.app/) 了解更多信息。)

2023-03-22 06:11 UTC, joker-bai commented
> > python/os_module
> 
> 这个 skill id 更新成 `python/os` 了，需要更新一下才能同步成功。后续因为 skills id 报错的，都可以到 skills tree 多维表格里面看一下新 id

关键是我这个challenge没有Python的skill，怎么会报这个错呢

2023-04-03 07:13 UTC, huhuhang requested changes

2023-04-03 07:13 UTC, huhuhang commented on kubernetes/challenge-kubernetes-advance-scheduler/solutions/solution-asset.md
需要将 solutions 拆分一下，绑定到 step。参考：https://www.labex.wiki/zh/basic/how-to-start#indexjson

2023-04-03 07:13 UTC, huhuhang commented on kubernetes/challenge-kubernetes-advance-scheduler/step5.md
> +     ![challenge-kubernetes-advance-scheduler-5-1](assets/challenge-kubernetes-advance-scheduler-5-1.png)
这个地方应该缩进到列表同级就行了吧。

2023-04-03 07:13 UTC, huhuhang commented on kubernetes/challenge-kubernetes-advance-scheduler/step5.md
> +     ![challenge-kubernetes-advance-scheduler-5-2](assets/challenge-kubernetes-advance-scheduler-5-2.png)
这个地方应该缩进到列表同级就行了吧。

2023-04-06 00:38 UTC, huhuhang approved these changes

2023-04-06 00:38 UTC, merged

2023-04-17 04:47 UTC, huhuhang commented
Hi, @joker-bai 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。