Add challenge word solitaire
labex-labs/scenarios pull request #163
Opened 2023-03-05 14:46 UTC by AyoungYa

# PR Checklist

Please post the link to the PR-related issue here (请将 PR 相关的 issues 的链接贴于此处):

Please make sure you've completed the relevant tasks for this PR from the following list (**请确保完成下方检查项，提交 PR 后才能打勾**):

- [ ] The structure of the lab/challenge is correct.(实验/挑战的结构正确)
- [ ] The format of the lab/challenge is correct.(实验/挑战的格式正确)
- [ ] The code and verification scripts have been tested in the environment.(代码和验证脚本在环境中测试通过，测试通过后请在 Labels 项添加 Test Complete)
- [ ] I promise that I have not plagiarised and have not copied the solution from other sources, AIGC is not included.(我保证没有抄袭，也没有从其他来源复制解决方案，AIGC 不包括在内)

See the [Contribution Guidelines](https://labex-docs.vercel.app/) for more details.(请参阅 [贡献指南](https://labex-docs.vercel.app/) 了解更多信息。)

2023-04-03 08:28 UTC, huhuhang requested changes

2023-04-03 08:28 UTC, huhuhang commented on python/challenge-word-solitaire/index.json
需要将 solutions  绑定到 step。参考：https://www.labex.wiki/zh/basic/how-to-start#indexjson

2023-04-03 15:14 UTC, AyoungYa commented on python/challenge-word-solitaire/index.json
done

2023-04-04 05:37 UTC, huhuhang requested changes

2023-04-04 05:37 UTC, huhuhang commented on python/challenge-word-solitaire/solutions/solitaire.py
> +    return result
Oh, no!

LabEx is a product aimed at English-speaking users.

2023-04-05 00:51 UTC, AyoungYa commented on python/challenge-word-solitaire/solutions/solitaire.py
> +    return result
done

2023-04-06 00:43 UTC, huhuhang requested changes

2023-04-06 00:43 UTC, huhuhang commented on python/challenge-word-solitaire/solutions/split_sentence.py
>  def process_sentence(sentence):
solution 的函数名和预留给用户的不一致，都需要检查一下。给用户的，和最终大概应该函数，变量等都是一样的。此外答案可以加上英文注释。

2023-04-06 00:43 UTC, huhuhang commented on python/challenge-word-solitaire/step1.md
> +# Sentence input and split
Title Case

2023-04-06 00:43 UTC, huhuhang commented on python/challenge-word-solitaire/step2.md
> +  Example:
缩进问题。

2023-04-06 00:43 UTC, huhuhang commented on python/challenge-word-solitaire/step2.md
> +- Repeat the previous step with the remaining words until all words are used.
这种一步一步的，可以用有序列表。

2023-04-07 14:52 UTC, AyoungYa commented on python/challenge-word-solitaire/solutions/split_sentence.py
>  def process_sentence(sentence):
漏网之鱼，已经修复

2023-04-07 14:52 UTC, AyoungYa commented on python/challenge-word-solitaire/step1.md
> +# Sentence input and split
done

2023-04-07 14:52 UTC, AyoungYa commented on python/challenge-word-solitaire/step2.md
> +  Example:
已经修改为有序列表

2023-04-07 14:52 UTC, AyoungYa commented on python/challenge-word-solitaire/step2.md
> +- Repeat the previous step with the remaining words until all words are used.
done

2023-04-10 01:11 UTC, huhuhang approved these changes

2023-04-10 01:11 UTC, huhuhang commented on python/challenge-word-solitaire/step2.md
> +3. Repeat the previous step with the remaining words until all words are used.
列表中间没有空行。我修复了。

2023-04-10 01:11 UTC, merged

2023-04-17 04:47 UTC, huhuhang commented
Hi, @AyoungYa 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。