Add challenge build fake person
labex-labs/scenarios pull request #165
Opened 2023-03-05 14:47 UTC by AyoungYa

# PR Checklist

Please post the link to the PR-related issue here (请将 PR 相关的 issues 的链接贴于此处):

Please make sure you've completed the relevant tasks for this PR from the following list (**请确保完成下方检查项，提交 PR 后才能打勾**):

- [ ] The structure of the lab/challenge is correct.(实验/挑战的结构正确)
- [ ] The format of the lab/challenge is correct.(实验/挑战的格式正确)
- [ ] The code and verification scripts have been tested in the environment.(代码和验证脚本在环境中测试通过，测试通过后请在 Labels 项添加 Test Complete)
- [ ] I promise that I have not plagiarised and have not copied the solution from other sources, AIGC is not included.(我保证没有抄袭，也没有从其他来源复制解决方案，AIGC 不包括在内)

See the [Contribution Guidelines](https://labex-docs.vercel.app/) for more details.(请参阅 [贡献指南](https://labex-docs.vercel.app/) 了解更多信息。)

2023-04-03 07:55 UTC, huhuhang requested changes
相似问题只批注一次，请一并修改。

2023-04-03 07:55 UTC, huhuhang commented on python/challenge-build-fake-person/verify1.sh
> +cd /tmp && python3 install_test.py
这个检测，其实 `pip list | grep Faker` 更简单吧。😄

2023-04-03 07:55 UTC, huhuhang commented on python/challenge-build-fake-person/verify1.sh
> +cd /tmp && python3 install_test.py
你这样写也行，只是搞复杂了。哈哈

2023-04-03 07:55 UTC, huhuhang commented on python/challenge-build-fake-person/step2.md
> +- Complete the getAge() method to return the correct age value.
`getAge()` 代码、路径、文件名等都需要用 markdown 单反引号的行内代码样式。

2023-04-03 07:55 UTC, huhuhang commented on python/challenge-build-fake-person/step2.md
> +- Complete the constructor method of the Person class and accept name, age, and email as three attributes.
- Complete the constructor method of the `Person` class and accept `name`, `age`, and `email` as three attributes.

代码、路径、文件名等都需要用 markdown 单反引号的行内代码样式。

变量名也是代码。

2023-04-03 07:55 UTC, huhuhang commented on python/challenge-build-fake-person/finish.md
> +In this challenge, you learned how to install and use a third library in Python.
…………

这个 challenge 的目的是学 Faker 包吧。。

2023-04-03 07:55 UTC, huhuhang commented on python/challenge-build-fake-person/index.json
需要将 solutions 拆分一下，绑定到 step。参考：https://www.labex.wiki/zh/basic/how-to-start#indexjson

2023-04-03 14:34 UTC, AyoungYa commented on python/challenge-build-fake-person/verify1.sh
> +cd /tmp && python3 install_test.py
确实不如直接用pip 方法检查方便

2023-04-03 14:35 UTC, AyoungYa commented on python/challenge-build-fake-person/step2.md
> +- Complete the constructor method of the Person class and accept name, age, and email as three attributes.
统一修改下

2023-04-03 14:35 UTC, AyoungYa commented on python/challenge-build-fake-person/index.json
1

2023-04-04 07:22 UTC, huhuhang approved these changes

2023-04-04 07:23 UTC, merged

2023-04-17 04:47 UTC, huhuhang commented
Hi, @AyoungYa 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。