Add challenge log parsing
labex-labs/scenarios pull request #166
Opened 2023-03-05 14:47 UTC by AyoungYa

# PR Checklist

Please post the link to the PR-related issue here (请将 PR 相关的 issues 的链接贴于此处):

Please make sure you've completed the relevant tasks for this PR from the following list (**请确保完成下方检查项，提交 PR 后才能打勾**):

- [ ] The structure of the lab/challenge is correct.(实验/挑战的结构正确)
- [ ] The format of the lab/challenge is correct.(实验/挑战的格式正确)
- [ ] The code and verification scripts have been tested in the environment.(代码和验证脚本在环境中测试通过，测试通过后请在 Labels 项添加 Test Complete)
- [ ] I promise that I have not plagiarised and have not copied the solution from other sources, AIGC is not included.(我保证没有抄袭，也没有从其他来源复制解决方案，AIGC 不包括在内)

See the [Contribution Guidelines](https://labex-docs.vercel.app/) for more details.(请参阅 [贡献指南](https://labex-docs.vercel.app/) 了解更多信息。)

2023-03-14 07:50 UTC, GodsDusk requested changes

2023-03-14 07:50 UTC, GodsDusk commented on python/challenge-log-parsing/intro.md
> +Our challenge is analysis this log file and the statistics each uri request count.
is analysis 两个动词了，建议是 is to analyse，语法内容先用 https://www.deepl.com/write 过一遍吧，后面的作者就先自查

2023-03-14 07:50 UTC, GodsDusk commented on python/challenge-log-parsing/assets/time_statistics.py
> +if __name__ == '__main__':
这部分代码似乎没必要，或者每个step给出的代码都包含这部分

2023-03-14 14:07 UTC, AyoungYa commented on python/challenge-log-parsing/intro.md
> +[Access.log](assets/access.log) is a log file that records access requests from others, each line means one-time access. The format of this file is `uri used_time`
这个题目是说有一个日志文件，要去解析，所以把文件的链接放到这里

2023-03-14 14:08 UTC, AyoungYa commented on python/challenge-log-parsing/assets/read_log.py
> +# -*- coding: utf-8 -*-
好的，这个我处理掉

2023-03-14 14:08 UTC, AyoungYa commented on python/challenge-log-parsing/intro.md
> +Our challenge is analysis this log file and the statistics each uri request count.
OK

2023-03-20 15:14 UTC, AyoungYa commented on python/challenge-log-parsing/assets/read_log.py
> +def read_log(file_name):
恩，done

2023-04-03 07:46 UTC, huhuhang requested changes

2023-04-03 07:46 UTC, huhuhang commented on python/challenge-log-parsing/index.json
需要将 solutions 绑定到 step。参考：https://www.labex.wiki/zh/basic/how-to-start#indexjson

2023-04-03 07:46 UTC, huhuhang commented on python/challenge-log-parsing/step1.md
> +Opening file: access.log and read the content in line, Print out each line and return the total number of lines at the end。
`access.log`

/
代码、路径、文件名等都需要用 markdown 单反引号的行内代码样式。

2023-04-03 07:46 UTC, huhuhang commented on python/challenge-log-parsing/solution/read_log.py
> +def read_log(file_name):
![CleanShot 2023-04-03 at 15 42 24](https://user-images.githubusercontent.com/5147530/229443696-39fda7dd-a688-40ac-9696-fb62f4cc7ed3.png)

答案要和预留的代码框架保持一致。

2023-04-03 07:46 UTC, huhuhang commented on python/challenge-log-parsing/solution/read_log.py
> +def read_log(file_name):
比如这里的 type hint 和 变量名 都不一样。

2023-04-03 07:48 UTC, huhuhang requested changes

2023-04-03 07:48 UTC, huhuhang commented on python/challenge-log-parsing/index.json
请注意放置答案代码的文件夹名称为 `solutions` 才能被正确绑定。

2023-04-03 14:13 UTC, AyoungYa commented on python/challenge-log-parsing/index.json
done

2023-04-03 14:20 UTC, AyoungYa commented on python/challenge-log-parsing/solution/read_log.py
> +def read_log(file_name):
done

2023-04-03 14:20 UTC, AyoungYa commented on python/challenge-log-parsing/step1.md
> +Opening file: access.log and read the content in line, Print out each line and return the total number of lines at the end。
之前还是这么写的，后面忘了参考哪个规则就去掉了

2023-04-10 01:13 UTC, huhuhang commented
@AyoungYa 行内代码样式都需要处理。👆

2023-04-11 14:03 UTC, AyoungYa commented
评论已经处理，请审核

2023-04-12 02:05 UTC, huhuhang requested changes
问题已经微信反馈。

2023-04-13 00:58 UTC, huhuhang requested changes
细心！细心！细心！一个 PR 改这么多次，大家都很痛苦。

2023-04-13 00:58 UTC, huhuhang commented on python/challenge-log-parsing/solutions/read_log.py
你的 solutions 文件和预留的代码框架还是风格不一样呢？solutions 就是在给学生的代码框架下进行补充。

2023-04-13 00:58 UTC, huhuhang commented on linux/challenge-linux-backup-log-file/intro.md
如果这个文件不是你修改的话，可以重新拉一个分支提交一下，避免修改其他 lab 的内容。

2023-04-17 01:14 UTC, huhuhang commented
@AyoungYa 麻烦你抽空重新拉一个分支提交一下这个 challenge，因为你的 PR 里面有修改其他的 challenge 记录（https://github.com/labex-labs/scenarios/pull/166/files#diff-f7895867113484982fc9c15e59916669778cec2ad702e741de4277c3719a95e1），这个估计只能重新开 PR 提交一下才能解决，否则合并后可能有问题。

2023-04-17 04:47 UTC, huhuhang commented
Hi, @AyoungYa 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。

2023-04-17 05:53 UTC, huhuhang commented
Hi, @AyoungYa 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。

如有疑问可以直接回复本条评论，或者微信联系。

2023-04-17 06:05 UTC, huhuhang commented
Hi, @AyoungYa 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。

如有疑问可以直接回复本条评论，或者微信联系。

2023-04-17 06:14 UTC, huhuhang commented
Hi, @AyoungYa 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。

如有疑问可以直接回复本条评论，或者微信联系。

2023-04-17 14:40 UTC, closed without merging