add jenkins install and pipeline
labex-labs/scenarios pull request #188
Opened 2023-03-06 07:33 UTC by joker-bai

# PR Checklist

Please post the link to the PR-related issue here (请将 PR 相关的 issues 的链接贴于此处):

Please make sure you've completed the relevant tasks for this PR from the following list (**请确保完成下方检查项，提交 PR 后才能打勾**):

- [ ] The structure of the lab/challenge is correct.(实验/挑战的结构正确)
- [ ] The format of the lab/challenge is correct.(实验/挑战的格式正确)
- [ ] The code and verification scripts have been tested in the environment.(代码和验证脚本在环境中测试通过，测试通过后请在 Labels 项添加 Test Complete)
- [ ] I promise that I have not plagiarised and have not copied the solution from other sources, AIGC is not included.(我保证没有抄袭，也没有从其他来源复制解决方案，AIGC 不包括在内)

See the [Contribution Guidelines](https://labex-docs.vercel.app/) for more details.(请参阅 [贡献指南](https://labex-docs.vercel.app/) 了解更多信息。)

2023-04-03 06:50 UTC, huhuhang requested changes

2023-04-03 06:50 UTC, huhuhang commented on jenkins/challenge-install-create-pipeline/step2.md
> +   ![challenge-install-create-pipeline-2-5](assets/challenge-install-create-pipeline-2-5.png)
操作命令除了截图提供，都需要以代码块的形式放到正文中。

2023-04-03 06:50 UTC, huhuhang commented on jenkins/challenge-install-create-pipeline/step3.md
> +5. Tomcat's default WEB port is `8080`, and we can use `http://127.0.0.1:8080/jenkins` to access the Jenkins service.
操作命令除了截图提供，都需要以代码块的形式放到正文中。

2023-04-03 06:50 UTC, huhuhang commented on jenkins/challenge-install-create-pipeline/step4.md
> +   ![challenge-install-create-pipeline-4-4](assets/challenge-install-create-pipeline-4-4.png)
操作命令除了截图提供，都需要以代码块的形式放到正文中。

2023-04-03 06:50 UTC, huhuhang commented on jenkins/challenge-install-create-pipeline/step5.md
> +   ![challenge-install-create-pipeline-5-3](assets/challenge-install-create-pipeline-5-3.png)
操作命令除了截图提供，都需要以代码块的形式放到正文中。

2023-04-03 06:50 UTC, huhuhang commented on jenkins/challenge-install-create-pipeline/index.json
> +    "imageid": "vnc-ubuntu:2204"
请确认是否不需要 instance 也可以。

2023-04-03 06:50 UTC, huhuhang commented on jenkins/challenge-install-create-pipeline/index.json
> +        ],
需要将 solutions 拆分一下，绑定到 step。参考：https://www.labex.wiki/zh/basic/how-to-start#indexjson

2023-04-03 06:56 UTC, huhuhang commented
代码块不需要处理，我一开始看错了，以为是 lab

2023-04-04 06:26 UTC, joker-bai commented on jenkins/challenge-install-create-pipeline/index.json
> +    "imageid": "vnc-ubuntu:2204"
这个challenge，不需要Instance，测试、过

2023-04-04 06:31 UTC, huhuhang requested changes
没问题，如果后续有需要附图解释得更清楚，也可以在 md 里面附图。

2023-04-04 06:40 UTC, joker-bai commented on jenkins/challenge-install-create-pipeline/solutions/step5-solution.md
> +4. In the `Script` text area, enter the following code:
好的

2023-04-04 06:57 UTC, huhuhang approved these changes

2023-04-04 06:57 UTC, merged

2023-04-17 04:46 UTC, huhuhang commented
Hi, @joker-bai 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。