add challenge-the-powerful-numpy-einsum-function
labex-labs/scenarios pull request #244
Opened 2023-03-08 11:50 UTC by Liugaga-vvv

# PR Checklist

Please post the link to the PR-related issue here (请将 PR 相关的 issues 的链接贴于此处):https://github.com/labex-labs/scenarios/issues/115

Please make sure you've completed the relevant tasks for this PR from the following list (**请确保完成下方检查项，提交 PR 后才能打勾**):

- [ ] The structure of the lab/challenge is correct.(实验/挑战的结构正确)
- [ ] The format of the lab/challenge is correct.(实验/挑战的格式正确)
- [ ] The code and verification scripts have been tested in the environment.(代码和验证脚本在环境中测试通过，测试通过后请在 Labels 项添加 Test Complete)
- [ ] I promise that I have not plagiarised and have not copied the solution from other sources, AIGC is not included.(我保证没有抄袭，也没有从其他来源复制解决方案，AIGC 不包括在内)

See the [Contribution Guidelines](https://labex-docs.vercel.app/) for more details.(请参阅 [贡献指南](https://labex-docs.vercel.app/) 了解更多信息。)

2023-03-10 01:07 UTC, GodsDusk requested changes

2023-03-10 01:07 UTC, GodsDusk commented on numpy/challenge-the-powerful-numpy-einsum-function/step1.md
> +You are given two matrices `A` and `B` of dimensions `(m x n)` and `(n x p)` respectively. Write a function `matmul(A, B)` that performs matrix multiplication between the two matrices using Numpy's e
公式使用 $ 符号，下同

2023-03-10 01:07 UTC, GodsDusk commented on numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product_test.py
> +        mock_einsum.assert_called_once_with('ij, ij -> ij', A, B)
所有test都缺少验证结果是否正确

2023-03-10 01:15 UTC, Liugaga-vvv commented on numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product_test.py
> +        mock_einsum.assert_called_once_with('ij, ij -> ij', A, B)
但是按照给的 mock_einsum.assert_called_once_with('ij, ij -> ij', A, B) 这个方法去验证的话 检验不了输出结果是否正确啊
expected_result = np.array([[25, 28], [57, 64], [89, 100]])
        matmul(A, B)
        mock_einsum.assert_called_once_with('ij, jk -> ik', A, B)

expected_result = np.array([[25, 28], [57, 64], [89, 100]])
        self.assertTrue(np.allclose(matmul(A, B), expected_result))
建议使用的验证方式 expected_result 不被调用 两种验证方式结合使用么

2023-03-10 01:36 UTC, GodsDusk commented on numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product_test.py
> +        mock_einsum.assert_called_once_with('ij, ij -> ij', A, B)
对，assertTrue和assert_called_once_with都要使用

2023-03-10 01:38 UTC, Liugaga-vvv commented on numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product_test.py
> +        mock_einsum.assert_called_once_with('ij, ij -> ij', A, B)
明白了 那我再改一下

2023-03-10 01:56 UTC, Liugaga-vvv commented on numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product_test.py
> +        mock_einsum.assert_called_once_with('ij, ij -> ij', A, B)
我试了一下 但是它提示我ValueError: operands could not be broadcast together with shapes (0,) (3,2)  所有的都是这个问题 是不是两个不能一起使用？

2023-03-10 05:43 UTC, GodsDusk commented on numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product_test.py
> +        mock_einsum.assert_called_once_with('ij, ij -> ij', A, B)
贴出完整代码

2023-03-10 05:50 UTC, Liugaga-vvv commented on numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product_test.py
> +        mock_einsum.assert_called_once_with('ij, ij -> ij', A, B)
import sys


sys.path.append("/home/labex/project")

import unittest
import numpy as np
from matmul import matmul
from unittest.mock import patch

class TestMatrixMultiplication(unittest.TestCase):
    @patch('numpy.einsum')
    def test_matmul(self, mock_einsum):
        A = np.array([[1, 2], [3, 4], [5, 6]])
        B = np.array([[7, 8], [9, 10]])
        
        expected_result = np.array([[25, 28], [57, 64], [89, 100]])
        self.assertTrue(np.allclose(matmul(A, B), expected_result))

        matmul(A, B)
        mock_einsum.assert_called_once_with('ij, jk -> ik', A, B)

if __name__ == '__main__':
    unittest.main()

提示的错误就是下面这个 好像是两个没办法一起使用
ValueError: operands could not be broadcast together with shapes (0,) (3,2)

2023-03-10 06:19 UTC, GodsDusk commented on numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product_test.py
> +        mock_einsum.assert_called_once_with('ij, ij -> ij', A, B)
assertTrue 和 assert_called_once_with 分别放在test 类的两个方法里执行

2023-03-10 08:29 UTC, Liugaga-vvv commented on numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product_test.py
> +        mock_einsum.assert_called_once_with('ij, ij -> ij', A, B)
解决好了

2023-03-10 08:53 UTC, GodsDusk requested changes

2023-03-10 08:53 UTC, GodsDusk commented on numpy/challenge-the-powerful-numpy-einsum-function/step1.md
> +You are given two matrices $A$ and $B$ of dimensions $(m x n)$ and $(n x p)$ respectively. Write a function `matmul(A, B)` that performs matrix multiplication between the two matrices using Numpy's e
$(n x p)$ 不要用英文的 x，环境里看文档很明显是英文 x，去找个在线 latex 公式编辑器看下乘号是怎么打出来的

2023-03-10 09:44 UTC, GodsDusk requested changes

2023-03-10 09:44 UTC, GodsDusk commented on numpy/challenge-the-powerful-numpy-einsum-function/step1.md
> +Write a function `matmul(A, B)` that performs matrix multiplication using Numpy's einsum function and returns the resulting matrix.
要说明这个 function 要写在哪里，下同

2023-03-10 09:44 UTC, GodsDusk commented on numpy/challenge-the-powerful-numpy-einsum-function/step5.md
> +# Einstein Summation Convention
这个 step 其实和 step1 重复了，删掉吧

2023-03-10 09:44 UTC, GodsDusk commented on numpy/challenge-the-powerful-numpy-einsum-function/step5.md
> +# Einstein Summation Convention
或者自己设计一个更难的也行

2023-03-10 10:19 UTC, Liugaga-vvv commented on numpy/challenge-the-powerful-numpy-einsum-function/step5.md
> +# Einstein Summation Convention
已解决  目前还设计不出来 以后一定能！

2023-03-10 14:25 UTC, GodsDusk requested changes

2023-03-10 14:25 UTC, GodsDusk commented on numpy/challenge-the-powerful-numpy-einsum-function/step1.md
> +2. Completing `matmul.py`
你这种写法没有连贯性，不觉得有点奇怪吗，
先实现函数，再完成脚本（完成脚本的什么？）

建议这样写就行 ：

Write a function `matmul(A, B)` in `matmul.py` 

下同

2023-03-12 02:40 UTC, GodsDusk approved these changes

2023-04-06 01:48 UTC, huhuhang commented
请 @GodsDusk 先确认一下。

2023-04-06 02:08 UTC, GodsDusk approved these changes

2023-04-06 03:15 UTC, huhuhang approved these changes

2023-04-06 03:15 UTC, merged

2023-04-17 04:46 UTC, huhuhang commented
Hi, @Liugaga-vvv 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。