Add challenge make numpy array your shape
labex-labs/scenarios pull request #246
Opened 2023-03-08 18:37 UTC by Beichen-Ma

# PR Checklist

Please post the link to the PR-related issue here (请将 PR 相关的 issues 的链接贴于此处): [#126 ](https://github.com/labex-labs/scenarios/issues/126)

Please make sure you've completed the relevant tasks for this PR from the following list (**请确保完成下方检查项，提交 PR 后才能打勾**):

- [ ] The structure of the lab/challenge is correct.(实验/挑战的结构正确)
- [ ] The format of the lab/challenge is correct.(实验/挑战的格式正确)
- [ ] The code and verification scripts have been tested in the environment.(代码和验证脚本在环境中测试通过，测试通过后请在 Labels 项添加 Test Complete)
- [ ] I promise that I have not plagiarised and have not copied the solution from other sources, AIGC is not included.(我保证没有抄袭，也没有从其他来源复制解决方案，AIGC 不包括在内)

See the [Contribution Guidelines](https://labex-docs.vercel.app/) for more details.(请参阅 [贡献指南](https://labex-docs.vercel.app/) 了解更多信息。)

2023-04-03 05:24 UTC, huhuhang requested changes

2023-04-03 05:24 UTC, huhuhang commented on numpy/challenge-make-numpy-array-your-shape/step1.md
> +### TODO
标题不能跨层级使用。

2023-04-03 05:24 UTC, huhuhang commented on numpy/challenge-make-numpy-array-your-shape/index.json
请按照新要求，补充一下 challenge 中的 solutions 字段。https://www.labex.wiki/zh/others/update-logs#20230323

2023-04-03 05:48 UTC, huhuhang requested changes

2023-04-03 05:48 UTC, huhuhang commented on numpy/challenge-make-numpy-array-your-shape/step1.md
> +Write a function `reshape_array(arr: np.ndarray, new_shape: tuple) -> np.ndarray` that takes in an array `arr` and a new shape `new_shape`, and returns a new Numpy array with the same data but a new
另外，Numpy 在正文和标题中的官方大小写应该是 NumPy。内容和 index.json 都需要搜索改一下。注意替换时不要把代码改了。

2023-04-13 07:37 UTC, Shuchong-LI requested changes
整体上没有大问题，注意以下几点：
1.英文文本尽量不要自己写，交由chatgpt或者翻译工具。自己写的文本如果不确定可以借助在线的enlish grammar check工具，尽量保持语言的准确性与书面性。
2.同样的问题注意记得在所有相关的文件里修改。

2023-04-13 07:37 UTC, Shuchong-LI commented on numpy/challenge-make-numpy-array-your-shape/assets/reshape_array.py
> +    # TODO: implement this function
首字母大写，句尾加 .

2023-04-13 07:37 UTC, Shuchong-LI commented on numpy/challenge-make-numpy-array-your-shape/solutions/solution.md
删掉此文件

2023-04-17 01:16 UTC, huhuhang commented
@Beichen-Ma 尽快解决。

2023-04-17 04:46 UTC, huhuhang commented
Hi, @Beichen-Ma 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。

2023-04-17 04:57 UTC, huhuhang commented
Hi, @Beichen-Ma 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。

2023-04-17 05:52 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review 

如有疑问可以直接回复本条评论，或者微信联系。

2023-04-20 02:54 UTC, Shuchong-LI requested changes
注意修改问题时所有地方都要修改。

2023-04-20 02:54 UTC, Shuchong-LI commented on numpy/challenge-make-numpy-array-your-shape/assets/concatenate_arrays.py
> +    # TODO: implement this function
Implement this function.

2023-04-20 02:54 UTC, Shuchong-LI commented on numpy/challenge-make-numpy-array-your-shape/assets/split_array.py
> +    # TODO: implement this function
同

2023-04-20 02:54 UTC, Shuchong-LI commented on numpy/challenge-make-numpy-array-your-shape/assets/stack_arrays.py
> +    # TODO: implement this function
同

2023-04-21 11:58 UTC, Shuchong-LI approved these changes

2023-04-23 00:41 UTC, huhuhang approved these changes

2023-04-23 00:41 UTC, merged