Challenge random number generation with numpy
labex-labs/scenarios pull request #251
Opened 2023-03-10 02:14 UTC by Liugaga-vvv

# PR Checklist

Please post the link to the PR-related issue here (请将 PR 相关的 issues 的链接贴于此处):https://github.com/labex-labs/scenarios/issues/247

Please make sure you've completed the relevant tasks for this PR from the following list (**请确保完成下方检查项，提交 PR 后才能打勾**):

- [ ] The structure of the lab/challenge is correct.(实验/挑战的结构正确)
- [ ] The format of the lab/challenge is correct.(实验/挑战的格式正确)
- [ ] The code and verification scripts have been tested in the environment.(代码和验证脚本在环境中测试通过，测试通过后请在 Labels 项添加 Test Complete)
- [ ] I promise that I have not plagiarised and have not copied the solution from other sources, AIGC is not included.(我保证没有抄袭，也没有从其他来源复制解决方案，AIGC 不包括在内)

See the [Contribution Guidelines](https://labex-docs.vercel.app/) for more details.(请参阅 [贡献指南](https://labex-docs.vercel.app/) 了解更多信息。)

2023-03-10 05:47 UTC, GodsDusk requested changes
注意issue最后我要求了test需要判断用户是否真的使用了random功能

2023-03-10 05:54 UTC, Liugaga-vvv commented
> 注意issue最后我要求了test需要判断用户是否真的使用了random功能

涉及到随机数操作，希望制作者对于检测脚本，能够判断用户是否真的使用了随机的功能：

1.强行规定随机数种子
2.检测脚本执行多次，至少有两次的结果不同
3.使用 unittest.mock.patch 判断用户是否使用相关函数，使用方法见 https://github.com/labex-labs/scenarios/issues/115#issuecomment-1451438098
以上3种方式任选一种，推荐第2种方式

我使用第二种方式了 检测脚本执行多次了

2023-03-10 06:25 UTC, GodsDusk commented
> > 注意issue最后我要求了test需要判断用户是否真的使用了random功能
> 
> 涉及到随机数操作，希望制作者对于检测脚本，能够判断用户是否真的使用了随机的功能：
> 
> 1.强行规定随机数种子 2.检测脚本执行多次，至少有两次的结果不同 3.使用 unittest.mock.patch 判断用户是否使用相关函数，使用方法见 [#115 (comment)](https://github.com/labex-labs/scenarios/issues/115#issuecomment-1451438098) 以上3种方式任选一种，推荐第2种方式
> 
> 我使用第二种方式了 检测脚本执行多次了

没在检测脚本里看出来你是怎么执行多次进行判断的。

比如以下方法可以直接通过第一步：

```
import numpy as np

def roll_dice() -> int:
    """Simulate the rolling of two six-sided dice and return the sum.

    Returns:
        int: The sum of the two dice rolls.
    """
    # TODO: implement this function
    # Note: Do not change the existing code
    return 3
```

2023-03-21 09:35 UTC, GodsDusk requested changes

2023-04-04 05:50 UTC, GodsDusk commented
> > > 注意issue最后我要求了test需要判断用户是否真的使用了random功能
> > 
> > 
> > 涉及到随机数操作，希望制作者对于检测脚本，能够判断用户是否真的使用了随机的功能：
> > 1.强行规定随机数种子 2.检测脚本执行多次，至少有两次的结果不同 3.使用 unittest.mock.patch 判断用户是否使用相关函数，使用方法见 [#115 (comment)](https://github.com/labex-labs/scenarios/issues/115#issuecomment-1451438098) 以上3种方式任选一种，推荐第2种方式
> > 我使用第二种方式了 检测脚本执行多次了
> 
> 没在检测脚本里看出来你是怎么执行多次进行判断的。
> 
> 比如以下方法可以直接通过第一步：
> 
> ```
> import numpy as np
> 
> def roll_dice() -> int:
>     """Simulate the rolling of two six-sided dice and return the sum.
> 
>     Returns:
>         int: The sum of the two dice rolls.
>     """
>     # TODO: implement this function
>     # Note: Do not change the existing code
>     return 3
> ```

你这个还是没改啊 😂
是没有思路吗？

2023-04-04 06:17 UTC, Liugaga-vvv commented
> > > > 注意issue最后我要求了test需要判断用户是否真的使用了random功能
> > > 
> > > 
> > > 涉及到随机数操作，希望制作者对于检测脚本，能够判断用户是否真的使用了随机的功能：
> > > 1.强行规定随机数种子 2.检测脚本执行多次，至少有两次的结果不同 3.使用 unittest.mock.patch 判断用户是否使用相关函数，使用方法见 [#115 (comment)](https://github.com/labex-labs/scenarios/issues/115#issuecomment-1451438098) 以上3种方式任选一种，推荐第2种方式
> > > 我使用第二种方式了 检测脚本执行多次了
> > 
> > 
> > 没在检测脚本里看出来你是怎么执行多次进行判断的。
> > 比如以下方法可以直接通过第一步：
> > ```
> > import numpy as np
> > 
> > def roll_dice() -> int:
> >     """Simulate the rolling of two six-sided dice and return the sum.
> > 
> >     Returns:
> >         int: The sum of the two dice rolls.
> >     """
> >     # TODO: implement this function
> >     # Note: Do not change the existing code
> >     return 3
> > ```
> 
> 你这个还是没改啊 😂 是没有思路吗？

改了几次但是都不行 没思路😂然后我还没点需要重新review 航哥可能看我昨天提交更改了 就帮我点了 最近在准备考研复试 也没怎么做工作😂

2023-04-04 08:04 UTC, GodsDusk commented
给你点提示：多次执行本质是参数估计的一个过程，比如你从一个黑盒里不断有放回地拿乒乓球，60次以后观察到取出的乒乓球颜色只有红黄蓝，那你是不是可以认为盒子里只有这三种颜色的乒乓球，然后在这60次里，每个颜色拿到的次数都在20左右，是不是可以认为三种颜色的乒乓球在盒子里的比例是一样的

2023-04-17 04:46 UTC, huhuhang commented
Hi, @Liugaga-vvv 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。

2023-04-17 04:57 UTC, huhuhang commented
Hi, @Liugaga-vvv 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。

2023-04-17 06:49 UTC, closed without merging