Challenge delete and move files
labex-labs/scenarios pull request #274
Opened 2023-03-17 14:51 UTC by Shuchong-LI

# PR Checklist

- fix #257 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-03-22 11:24 UTC, xinxin68 requested changes

2023-03-22 11:24 UTC, xinxin68 commented on linux/challenge-delete-and-move-files/intro.md
> +* `rm` - remove files or directories
应为无序列表 - 而不是 * ，下同

2023-03-22 11:24 UTC, xinxin68 commented on linux/challenge-delete-and-move-files/verify1.sh
> +cat ~/.zsh_history | grep -q "rm mytextfile.txt"
检测这么写大概率是过不了的，多一个少一个空格就不匹配了，这类检测可以直接 grep >> 和 >，然后再看看文件里的内容对不对，最后要更严格可以检测是否使用了 vim 或者 nano 之类的编辑器。下同

2023-03-22 11:24 UTC, xinxin68 commented on linux/challenge-delete-and-move-files/verify3-1.sh
> +ls -l /home/labex/Desktop/ | grep "challenge3" | grep "rwxrwxrwx"
这最终能实现什么效果呢？应该加一个判断吧

2023-04-03 03:18 UTC, huhuhang approved these changes
Nice Work!

2023-04-03 03:19 UTC, merged

2023-04-17 04:45 UTC, huhuhang commented
Hi, @xinxin68 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review