add linux/challenge-mastering-text-manipulation
labex-labs/scenarios pull request #280
Opened 2023-03-20 08:33 UTC by GuoJiang-yw

# PR Checklist

- fix #265

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-03-22 12:14 UTC, xinxin68 requested changes

2023-03-22 12:14 UTC, xinxin68 commented on linux/challenge-mastering-text-manipulation/intro.md
> +# Mastering-Text-Manipulation
标题与标题之间应该有空行

2023-03-22 12:14 UTC, xinxin68 commented on linux/challenge-mastering-text-manipulation/step1.md
> +# Step 1 title:Search for specific lines using grep.
标题与标题之间应该有空行，下同。

2023-03-22 12:14 UTC, xinxin68 commented on linux/challenge-mastering-text-manipulation/verify1.sh
> +#!/bin/bash
这不是检测脚本的内容，是每个步骤所对应的参考答案即Solution的内容。下同

2023-03-22 12:14 UTC, xinxin68 commented on linux/challenge-mastering-text-manipulation/solution/solution.md
> +# Solution
这里面应该有每个步骤解决问题代码。

2023-03-22 14:02 UTC, GuoJiang-yw commented
脚本检测没有输出结果

2023-04-06 01:28 UTC, huhuhang requested changes

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/solution/.solution.md.swp
多余的文件需要被移除。

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/solution/solution.md
需要将 solutions 绑定到 step。参考：https://www.labex.wiki/zh/basic/how-to-start#indexjson

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/solution/solution.md
需要拆成多个 step solution 文件，可以参考 master 分支里面的 challenge。

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/index.json
> +    "title": "Mastering-Text-Manipulation",
title 中没有 -

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/intro.md
> +# Mastering-Text-Manipulation
Title 没有短横线

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/intro.md
> +- sed:  stream editor for modifying text data
1. 冒号后面有 2 个空格。
2. 代码、路径、文件名等都需要用 markdown 单反引号的行内代码样式。

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/step1.md
> +# Search for specific lines using grep
Title Case

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/step1.md
> +```
这里需要补充一下 `example.txt` 中可以多添加 2 行没有 line 的内容。这样 `grep` 前后就有对比了。

这个 issue 开得不好，不是你的问题。

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/step2.md
> +# Extract specific fields Using awk
Title Case

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/step3.md
> +# Replace text in a file using sed
Title Case

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/step3.md
> +```
同 step1，前后需要有对比，可能需要改一下数据。

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/step1.md
> +Suppose you have a file called `example.txt` that contains the following lines of text:
`example.txt` 要用 `setup.sh` 提前给用户创建好。https://www.labex.wiki/zh/basic/how-to-start#%E5%9F%BA%E6%9C%AC%E7%BB%93%E6%9E%84

除非你新增 1 个 step 考文件的创建。否则在这个 grep 的内容中，不应该需要用户自己创建文件。

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/step1.md
> +Suppose you have a file called `example.txt` that contains the following lines of text:
并且这个文件在哪个路径下很关键，否则用户随便创建一个 example.txt，你肯定检测不到。

2023-04-06 01:28 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/verify1-2.sh
> +#rm -rf  test_output1.txt
你需要检测的是用户是否用 grep 操作完成了步骤的目标，而不是你自己的检测脚本 grep 完成目标后进行对比。

你这样检测 100% 会通过呢，因为你的操作本来就是答案。

再仔细理一下逻辑。

2023-04-06 10:49 UTC, GuoJiang-yw commented on linux/challenge-mastering-text-manipulation/solution/.solution.md.swp
没有这个文件

2023-04-06 11:21 UTC, GuoJiang-yw commented on linux/challenge-mastering-text-manipulation/step3.md
> +```
这个是有变化的，用sed命令将text.txt中的line替换成了string

2023-04-06 11:26 UTC, GuoJiang-yw commented on linux/challenge-mastering-text-manipulation/step1.md
> +Suppose you have a file called `example.txt` that contains the following lines of text:
challenge不是要自己动手操作吗？
我的verify脚本检测文件中有检测example.txt是否在/home/labex/路径下存在，如果不存在就不能进入下一步

2023-04-06 11:38 UTC, GuoJiang-yw commented on linux/challenge-mastering-text-manipulation/step1.md
> +Suppose you have a file called `example.txt` that contains the following lines of text:
用户是不是只需要进行grep的操作，不需要自己创建文件

2023-04-06 12:21 UTC, GuoJiang-yw commented
> Error in PR synchronization!

这是什么问题，我的文件都是创建了的

2023-04-06 14:53 UTC, GuoJiang-yw commented
我知道原因了，solution文件夹的名字没有加s

2023-04-07 01:07 UTC, huhuhang requested changes

2023-04-07 01:07 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/solution/.solution.md.swp
我都能批注这个文件，怎么会没有这个文件？

2023-04-07 01:07 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/step3.md
> +```
OK

2023-04-07 01:07 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/step1.md
> +Suppose you have a file called `example.txt` that contains the following lines of text:
那你需要指定一下文件创建的路径，否则用户是不是不知道在哪个目录下创建？

2023-04-07 02:40 UTC, GuoJiang-yw commented
你批注的是之前提交的内容，现在没有了

2023-04-07 06:04 UTC, huhuhang requested changes

2023-04-07 06:04 UTC, huhuhang commented on linux/challenge-mastering-text-manipulation/verify2-2.sh
> +#rm -rf test_output2.txt
把这些不要的内容可以删掉。

2023-04-07 07:04 UTC, huhuhang approved these changes

2023-04-07 07:05 UTC, merged

2023-04-17 04:45 UTC, huhuhang commented
Hi, @xinxin68 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review