add itertools module lab
labex-labs/scenarios pull request #288
Opened 2023-03-22 07:34 UTC by joker-bai

# PR Checklist

- fix #285

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-03-23 01:29 UTC, GodsDusk requested changes

2023-03-23 01:29 UTC, GodsDusk commented on python/lab-itertools-module/step1.md
> +Create a Project called `chain.py` in WebIDE and enter the following content.
如果要用户在文件中操作，那应该在 asserts 中提供对应的文件给用户；或者也可以不用文件，让用户直接在终端操作

2023-03-23 01:29 UTC, GodsDusk commented on python/lab-itertools-module/index.json
> +        "skills": []
缺少skills

2023-03-23 01:29 UTC, GodsDusk commented on python/lab-itertools-module/intro.md
> +```
每个md都需要用prettier格式化一下

2023-03-23 03:07 UTC, joker-bai commented on python/lab-itertools-module/index.json
> +        "skills": []
上次huhuhang说如果是相同的skills，只需要写 一个即可，要每一个都写么

2023-03-23 03:15 UTC, GodsDusk commented on python/lab-itertools-module/index.json
> +        "skills": []
> 上次huhuhang说如果是相同的skills，只需要写 一个即可，要每一个都写么

我看了聊天记录，是要都写上的

> 我又仔细想了一下，感觉这样会留下隐患，还是复制粘贴一份吧。😂 步骤重复 skills，我们最终也可以统计用户练习这个 skills 的次数。如果留空，这个步骤就统计不到了。

2023-03-23 05:36 UTC, joker-bai commented on python/lab-itertools-module/index.json
> +        "skills": []
好的

2023-03-23 06:29 UTC, joker-bai commented on python/lab-itertools-module/intro.md
> +```
这个每个文档我都用了prettier格式化，没看出啥差别~~

2023-03-23 07:10 UTC, GodsDusk requested changes

2023-03-23 07:10 UTC, GodsDusk commented on python/lab-itertools-module/assets/chain.py
> +import itertools
提供空文件就行了 😂，下同

2023-03-23 07:10 UTC, GodsDusk commented on python/lab-itertools-module/step1.md
> +Input `python chain.py` in Terminal. Then check the output.
`python chain.py` 单独一行吧，方便用户复制黏贴

2023-03-23 07:10 UTC, GodsDusk commented on python/lab-itertools-module/verify1-1.sh
> +cd /home/labex/project/ && python chain.py
就算提供空文件，就算用户什么都不做都可以通过，建议是检测用户是否在终端执行脚本就行

2023-03-23 07:13 UTC, joker-bai commented on python/lab-itertools-module/assets/chain.py
> +import itertools
我就在纳闷，我都写了，还要读者写啥，哈哈

2023-03-23 07:25 UTC, joker-bai commented on python/lab-itertools-module/verify1-1.sh
> +cd /home/labex/project/ && python chain.py
大哥，修改了

2023-03-23 07:55 UTC, GodsDusk approved these changes

2023-04-03 05:10 UTC, huhuhang requested changes
内容问题不大，检测脚本需要优化一下。

2023-04-03 05:10 UTC, huhuhang commented on python/lab-itertools-module/verify1-1.sh
检测脚本有 https://github.com/labex-labs/scenarios/pull/322 同样的问题，都需要处理。

2023-04-04 05:04 UTC, huhuhang approved these changes

2023-04-04 05:05 UTC, merged

2023-04-17 04:45 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review