Lab typing module
labex-labs/scenarios pull request #294
Opened 2023-03-23 05:59 UTC by joker-bai

# PR Checklist

- fix #286

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-03-23 07:23 UTC, GodsDusk commented on python/lab-typing-module/assets/example.py
> +def add_numbers(x: int, y: int) -> int:
空文件就行，让用户自己实现

2023-03-23 07:23 UTC, GodsDusk commented on python/lab-typing-module/step1.md
> +```
每个step都要进入退出python console体验有点差。。

2023-03-23 07:23 UTC, GodsDusk commented on python/lab-typing-module/step3.md
> +class Person:
这种有多个缩进的在console里操作太不友好了，用文件或者ipython吧，文件的话整个实验似乎有点多，可以多个操作放一个文件，或者用文件夹

2023-03-23 07:26 UTC, joker-bai commented on python/lab-typing-module/step1.md
> +```
我发现这个用命令行检测脚本，有时候不退出，压根检测不到

2023-03-23 08:06 UTC, joker-bai commented on python/lab-typing-module/step3.md
> +class Person:
已修改

2023-04-03 05:03 UTC, huhuhang requested changes
整个 PR 做得挺好的，这个原本的 issue 质量不高。

相似问题需要一并处理。

2023-04-03 05:03 UTC, huhuhang commented on python/lab-typing-module/step2.md
> +2; Define a variable of type Dict[str, int], assign it some key-value pairs, and print it.
`Dict[str, int]` 
代码、路径、文件名等都需要用 markdown 单反引号的行内代码样式。

2023-04-03 13:13 UTC, joker-bai commented
已经修改 @huhuhang

2023-04-04 04:47 UTC, huhuhang approved these changes

2023-04-04 05:02 UTC, merged

2023-04-17 04:45 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review