Add lab-collections-module
labex-labs/scenarios pull request #298
Opened 2023-03-23 09:37 UTC by AsukaLove2

# PR Checklist

- fix #283 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-03-23 09:47 UTC, AsukaLove2 commented
@GodsDusk 老师，测试完了，麻烦你检查一下

2023-03-23 09:54 UTC, GodsDusk requested changes

2023-03-23 09:54 UTC, GodsDusk commented on python/lab-collections-module/step1.md
> +A `namedtuple` is a subclass of a tuple, providing named fields for more readability and self-documenting code. Let's create a `namedtuple` in `demo1.py` to represent a point in a 2D space:
文件名太随意了

2023-03-23 09:54 UTC, GodsDusk commented on python/lab-collections-module/step1.md
> +from collections import namedtuple
代码块中注释尽量都加上

2023-03-23 09:54 UTC, GodsDusk commented on python/lab-collections-module/step1.md
> +First, let's import the collections module:
这句没头没尾的，在哪 import ?

2023-03-23 09:54 UTC, GodsDusk commented on python/lab-collections-module/step1.md
> +Output:
如何执行才有这个output？

2023-03-23 10:42 UTC, AsukaLove2 commented
@GodsDusk 老师，我改好了，麻烦你再看看吧

2023-03-23 14:04 UTC, GodsDusk requested changes

2023-03-23 14:04 UTC, GodsDusk commented on python/lab-collections-module/step1.md
> +Then, press F5 to run the program. If prompted to select debug configuration, select the Python file.
不要用 F5，用终端执行指令来操作脚本

2023-03-23 14:28 UTC, AsukaLove2 commented on python/lab-collections-module/step1.md
> +Then, press F5 to run the program. If prompted to select debug configuration, select the Python file.
老师，我有点不明白了。这个终端是指什么啊？是指点击上面那个Run里的选项来运行程序吗？虽然有这种可能，但真的需要我们来教用户怎么运行程序吗。。。
如果终端不是点击Run里的选项的话，那是下面这个Terminal吗？可环境不是在webide里面吗，这里面也要用命令的形式运行程序吗?

2023-03-24 00:31 UTC, GodsDusk commented on python/lab-collections-module/step1.md
> +Then, press F5 to run the program. If prompted to select debug configuration, select the Python file.
![WX20230324-083031@2x](https://user-images.githubusercontent.com/13726533/227393566-0e2d00da-3063-4a53-967c-2e70465415dc.png)

webide 统一用这种方式

2023-03-24 01:48 UTC, AsukaLove2 commented on python/lab-collections-module/step1.md
> +Then, press F5 to run the program. If prompted to select debug configuration, select the Python file.
明白了，老师。
我改好了老师，麻烦你再看看

2023-03-24 02:35 UTC, GodsDusk requested changes

2023-03-24 02:35 UTC, GodsDusk commented on python/lab-collections-module/step1.md
> +Then, debug your script by typing python in the terminal below, such as python `namedtuple.py`
表述还是差点意思，给个最基本的表述：

Then, run the script in the terminal:
```bash
python namedtuple.py
```

自己再修改下

2023-03-24 02:45 UTC, AsukaLove2 commented on python/lab-collections-module/step1.md
> +Then, debug your script by typing python in the terminal below, such as python `namedtuple.py`
好的老师，这确实是我的英文表述水平不好的原因。
我改好了，麻烦老师再看看

2023-03-24 05:41 UTC, GodsDusk requested changes

2023-03-24 05:41 UTC, GodsDusk commented on python/lab-collections-module/step1.md
> +#Import collections
\# 后的空格还是需要的，都补上，再用格式化工具检查一下所有文件

2023-03-24 05:41 UTC, GodsDusk commented on python/lab-collections-module/step3.md
> +```
每个step需要加上检测用户是否执行脚本的verify

2023-03-24 07:58 UTC, AsukaLove2 commented on python/lab-collections-module/step3.md
> +```
老师，我添加好了。麻烦你再看看吧

2023-03-24 08:45 UTC, GodsDusk requested changes

2023-03-24 08:45 UTC, GodsDusk commented on python/lab-collections-module/step4.md
> +    word_count3[word] = word_count3[word]
这两步是在干什么？

2023-03-24 08:45 UTC, GodsDusk commented on python/lab-collections-module/step4.md
> +{'the': set(), 'quick': set(), 'brown': set(), 'fox': set(), 'jumps': set(), 'over': set(), 'lazy': set(), 'dog': set()}
list 和 set 的结果有什么意义？

2023-03-24 08:45 UTC, GodsDusk commented on python/lab-collections-module/step1.md
> +A `namedtuple` is a subclass of a tuple, providing named fields for more readability and self-documenting code. Let's create a `namedtuple` in `namedtuple.py` to represent a point in a 2D space:
文件名命名也要遵循下划线命名规则，如果是一个单词就不用下划线，不然要用下划线隔开

2023-03-24 10:23 UTC, AsukaLove2 commented on python/lab-collections-module/step4.md
> +{'the': set(), 'quick': set(), 'brown': set(), 'fox': set(), 'jumps': set(), 'over': set(), 'lazy': set(), 'dog': set()}
老师，我尽力去表达我加的语句的解释了。你再看看行不行。如果还是不行的话，请老师指点一下吧。

2023-03-25 04:17 UTC, GodsDusk requested changes

2023-03-25 04:17 UTC, GodsDusk commented on python/lab-collections-module/step4.md
> +{'the': set(), 'quick': set(), 'brown': set(), 'fox': set(), 'jumps': set(), 'over': set(), 'lazy': set(), 'dog': set()}
> 老师，我尽力去表达我加的语句的解释了。你再看看行不行。如果还是不行的话，请老师指点一下吧。

去搜一下 `defaultdict(list)` 和 `defaultdict(set)` 是怎么使用的

2023-03-25 08:49 UTC, AsukaLove2 commented
@GodsDusk 老师，我改好了，麻烦你再检查一下

2023-03-25 10:44 UTC, GodsDusk requested changes

2023-03-25 10:44 UTC, GodsDusk commented on python/lab-collections-module/step4.md
> +`DefaultDict` is a subclass of dict that provides a default value for a nonexistent key. Let's create a `DefaultDict` with default values 0, [], and set() in `default_dict.py` and count the occurrenc
这段表述和下面的实验不一致，而且注意要 `[]`, and `set()` ，其实最好下面的拆成两个脚本，另外告诉用户，在不使用DefaultDict时，相同实现的python代码是如何的复杂

2023-03-25 10:44 UTC, GodsDusk commented on python/lab-collections-module/step5.md
> +print(d)
这个步骤print太多，用户要一一比较比较麻烦，在print里加上这一步的内容，比如 `print('Append to the right:', d)`

2023-03-25 10:44 UTC, GodsDusk commented on python/lab-collections-module/step4.md
> +data = [('a', 1), ('a', 1), ('a', 3), ('b', 1), ('b', 2), ('b', 3)]
其实用 sentence 就可以有使用 list 和 set 的例子了，不过你用了别的，最好还是拆开分别说明

2023-03-27 04:50 UTC, AsukaLove2 commented
@GodsDusk 老师，我改好了，麻烦你再看看吧

2023-03-27 06:27 UTC, GodsDusk requested changes

2023-03-27 06:27 UTC, GodsDusk commented on python/lab-collections-module/step4.md
> +# DefaultDict
用二级标题 ## 切分一下这个step

2023-03-27 06:27 UTC, GodsDusk commented on python/lab-collections-module/step4.md
> +`DefaultDict` is a subclass of dict that provides a default value for a nonexistent key. Let's create a `DefaultDict` with default values 0 in `default_dict1.py` and count the occurrences of words in
`0`

2023-03-27 06:27 UTC, GodsDusk commented on python/lab-collections-module/step4.md
> +Next, Let's create a `DefaultDict` with default values [] in `default_dict2.py` and store the number in each letter:
`[]`

2023-03-27 06:27 UTC, GodsDusk commented on python/lab-collections-module/step4.md
> +Finally, Let's create a `DefaultDict` with default values set() in `default_dict3.py` and stores the number that is not repeated in each letter:
`set()`

2023-03-27 07:13 UTC, AsukaLove2 commented on python/lab-collections-module/step4.md
> +Finally, Let's create a `DefaultDict` with default values set() in `default_dict3.py` and stores the number that is not repeated in each letter:
老师，我改好了。麻烦你再看看

2023-03-27 07:15 UTC, GodsDusk requested changes

2023-03-27 07:15 UTC, GodsDusk commented on python/lab-collections-module/step4.md
> +Finally, Let's create a `DefaultDict` with default values set() in `default_dict3.py` and stores the number that is not repeated in each letter:
> 老师，我改好了。麻烦你再看看

你理解错我的意思了，这个comment是说文本里的 set() 要改成 `set()` 😂，你再改一下，注意标题也不要太随意了

2023-03-27 07:47 UTC, GodsDusk approved these changes

2023-04-03 04:21 UTC, huhuhang requested changes

2023-04-03 04:21 UTC, huhuhang commented on template/challenge-new-challenge/finish.md
注意看一下文件变更，你的 PR 合并后会把主分支的 template 删除。

2023-04-03 06:07 UTC, AsukaLove2 commented on template/challenge-new-challenge/finish.md
知道了老师。那是要我做些什么吗，这个template被删除应该没什么影响吧。如果没影响的话老师你就合并就行。

2023-04-10 01:21 UTC, huhuhang commented
@AsukaLove2 你的文件提交还是有问题，会影响到我们主分支的 template 文件夹。重新拉分支提交 PR。

2023-04-10 01:21 UTC, closed without merging