add lnmp lab
labex-labs/scenarios pull request #312
Opened 2023-03-24 07:35 UTC by joker-bai

# PR Checklist

- fix #307

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-04-03 06:19 UTC, huhuhang requested changes
这个内容必须要 instance 环境吗？感觉 docker 也行？你判断一下即可。

2023-04-03 06:19 UTC, huhuhang commented on linux/lab-linux-deploy-lnmp/index.json
> +        "title": "Configure Mysql",
MySQL

2023-04-03 06:19 UTC, huhuhang commented on linux/lab-linux-deploy-lnmp/index.json
> +        "title": "Configure Php",
PHP

2023-04-03 06:19 UTC, huhuhang commented on linux/lab-linux-deploy-lnmp/step1.md
> +1; Update package lists: Run the following command to update the package lists on the server:
规范的 md 序号。

2023-04-03 06:19 UTC, huhuhang commented on linux/lab-linux-deploy-lnmp/step1.md
> +sudo apt-get install nginx
建议安装的版本指定为 1.18.0，这样后面维护成本低。

2023-04-03 06:19 UTC, huhuhang commented on linux/lab-linux-deploy-lnmp/step2.md
> +# Install Mysql
MySQL

2023-04-03 06:19 UTC, huhuhang commented on linux/lab-linux-deploy-lnmp/step4.md
此步骤不操作也可以 PASS

2023-04-03 10:06 UTC, joker-bai commented
修改完了 @huhuhang

2023-04-04 04:45 UTC, huhuhang approved these changes

2023-04-04 04:45 UTC, merged

2023-04-17 04:45 UTC, huhuhang commented
Hi, @joker-bai 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review