lab-variables-and-memory-addresses
labex-labs/scenarios pull request #320
Opened 2023-03-24 15:40 UTC by wanliqin

# PR Checklist

- fix #281

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-03-25 04:29 UTC, GodsDusk requested changes
写作并不是从issue中复制黏贴下来就可以了，自己也要体验流程的通畅性

2023-03-25 04:29 UTC, GodsDusk commented on python/lab-variables-and-memory-addresses/index.json
> +  "description": "In this tutorial, we'll dive deeper into Python variables and memory addresses. We'll learn about variable assignment, mutable and immutable data types, and the `is` operator for co
描述太长了，再短一点

2023-03-25 04:29 UTC, GodsDusk commented on python/lab-variables-and-memory-addresses/intro.md
> +## Variable Assignment and Memory Addresses
intro简单介绍即可，基本不需要给出代码和步骤，实现都是在step中

2023-03-25 04:29 UTC, GodsDusk commented on python/lab-variables-and-memory-addresses/step1.md
> +## Solution:
名称不应该叫 solution 吧，应该是 example，之类的

2023-03-25 04:29 UTC, GodsDusk commented on python/lab-variables-and-memory-addresses/finish.md
> +In this advanced tutorial, we delved deeper into Python variables and memory addresses. We discussed variable assignment, mutable and immutable data types, and the `is` operator for comparing memory
difficulty 是 Beginner，结束了说是 advanced tutorial， 这类逻辑也要检查一下

2023-03-25 04:29 UTC, GodsDusk commented on python/lab-variables-and-memory-addresses/intro.md
> +x = [1, 2, 3]
代码注释尽量多写

2023-03-25 04:29 UTC, GodsDusk commented on python/lab-variables-and-memory-addresses/step1.md
> +```
最后要一个小的 Conclusion，比如你可以把括号里的放这里，注释简单说明即可

2023-04-03 09:15 UTC, huhuhang requested changes

2023-04-03 09:15 UTC, huhuhang commented on python/lab-variables-and-memory-addresses/index.json
> +    "title": "Lab-Variables-and-Memory-Addresses",
title 格式错误。

2023-04-03 09:15 UTC, huhuhang commented on python/lab-variables-and-memory-addresses/step0.md
> +
首先要 open terminal，参考 https://github.com/labex-labs/scenarios/pull/249/files#diff-1bab7f6d7764566e9999bcaca10d2ad9907a8f199ea9a6244f56062179d57bea

2023-04-03 09:15 UTC, huhuhang commented on python/lab-variables-and-memory-addresses/step0.md
step 从 step1 开始。除非对于一些已完成内容，整体 step 序号改动比较麻烦的前提下，才可以添加 step0

2023-04-03 09:15 UTC, huhuhang commented on python/lab-variables-and-memory-addresses/step0.md
> +
无意义段落。

2023-04-07 05:59 UTC, huhuhang requested changes
内容在提交前需要使用 prettier 进行格式化处理。https://www.labex.wiki/zh/basic/formatting-guide#%E6%96%87%E6%A1%A3

2023-04-07 05:59 UTC, huhuhang commented on python/lab-variables-and-memory-addresses/step2.md
> +# Compare memory addresses of mutable and immutable data types
title case

2023-04-07 05:59 UTC, huhuhang commented on python/lab-variables-and-memory-addresses/step2.md
> +# Compare memory addresses of mutable and immutable data types
the title is too long.

Compare Memory Addresses

2023-04-07 05:59 UTC, huhuhang commented on python/lab-variables-and-memory-addresses/step2.md
> +2. mutable data types with the same value have different memory addresses.
句子首字母大写。

2023-04-07 05:59 UTC, huhuhang commented on python/lab-variables-and-memory-addresses/finish.md
> +# Conclusion
模板是 Summary

2023-04-07 05:59 UTC, huhuhang commented on python/lab-variables-and-memory-addresses/step3.md
> +# Modifying a mutable data type
Title Case

2023-04-07 05:59 UTC, huhuhang commented on python/lab-variables-and-memory-addresses/step4.md
> +# Modifying an immutable data type
Title Case

2023-04-10 01:24 UTC, huhuhang commented
The intern withdrew, and LabEx will revise this PR.

2023-04-10 01:24 UTC, merged