add challenge-error-and-exception-handling
labex-labs/scenarios pull request #321
Opened 2023-03-25 11:06 UTC by Liang-jonas

# PR Checklist

- fix #306

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-03-28 02:12 UTC, GodsDusk requested changes

2023-03-28 02:12 UTC, GodsDusk commented on python/challenge-error-and-exception-handling/verify3.sh
> +cd /tmp && cp /home/labex/project/step3.py /tmp/ && cp /home/labex/project/example.txt /tmp && python3 step3.py
这个你理解错我的意思了，我举个例子把，比如你要检测 `test_read_data_from_file_success` 这个用户是否实现正确是吧，如果用你的方法，用户用

```python
    def test_read_data_from_file_success(self):
        # TODO: Verify that the output is the contents of example.txt.
        pass
```

是可以通过检测的，但正确答案应该是

```python
def test_read_data_from_file_success(self):
        result = read_data_from_file('/home/labex/project/example.txt')
        self.assertEqual(result, 'example content')
```
那我们可以准备两个文件夹，一个文件夹里的是正确的 example.txt，检查是否正确通过：

```bash
cd /tmp
mkdir test1
cd test1
cp /home/labex/project/step3.py .
echo "example content" >> example.txt
python -m unittest step3.py
```

另一个是错误的 example.txt，检查是否能判断错误：

```bash
cd /tmp
mkdir test2
cd test2
cp /home/labex/project/step3.py .
echo "example contents" >> example.txt
python -m unittest step3.py
```

此时执行，就会不通过：

```bash
.....F
======================================================================
FAIL: test_read_data_from_file_success (step3.TestErrorHandlingChallenge)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/labex/project/step3.py", line 18, in test_read_data_from_file_success
    self.assertEqual(result, 'example content')
AssertionError: 'example contents' != 'example content'
- example contents
?                -
+ example content


----------------------------------------------------------------------
Ran 6 tests in 0.001s

FAILED (failures=1)
```

你可以从上面挑一段判断是否出现

2023-03-29 02:23 UTC, GodsDusk requested changes

2023-03-29 02:23 UTC, GodsDusk commented on python/challenge-error-and-exception-handling/verify1-7.sh
> +fi
这个将 bac mv 的操作没起作用，再测试一下

2023-03-29 09:55 UTC, GodsDusk requested changes

2023-03-29 09:55 UTC, GodsDusk commented on python/challenge-error-and-exception-handling/step1.md
> +There is a piece of code in `step1.py` that is designed to read from the `example.txt` file we provided and do some processing, now you need to add some exception handling to this code. The content o
`step1.py` 起名太随意了，尽量跟小标题带点关系，太长了可以缩写或者精简，下同

2023-03-30 01:08 UTC, GodsDusk approved these changes

2023-03-30 01:10 UTC, GodsDusk commented
做完这个challenge，我觉得你可以尝试自己开一下对应的lab了

2023-04-03 03:36 UTC, huhuhang approved these changes
Nice Work!

2023-04-03 03:36 UTC, huhuhang commented on python/challenge-error-and-exception-handling/step1.md
> +### Create custom exception classes
所有的 title 都需要 title case。

2023-04-03 03:36 UTC, merged

2023-04-17 04:45 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review