add lab-array-attributes-and-dtype
labex-labs/scenarios pull request #324
Opened 2023-03-28 04:28 UTC by Aixiiba

# PR Checklist

- fix #ID

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-03-29 02:01 UTC, GodsDusk requested changes

2023-03-29 02:01 UTC, GodsDusk commented on python/lab-array-attributes-and-dtype/step3.md
> +
多余的空行，下面也是

2023-03-29 02:01 UTC, GodsDusk commented on python/lab-array-attributes-and-dtype/step3.md
> +print("Zeros array with dtype uint8:\n", zeros_array)
这里的 # Output呢？

2023-04-04 08:07 UTC, GodsDusk requested changes

2023-04-04 08:07 UTC, GodsDusk commented on python/lab-array-attributes-and-dtype/verify3.sh
> +grep -E "dtype" ~/.python_history
依然什么都没执行就通过了

2023-04-06 10:04 UTC, GodsDusk requested changes

2023-04-06 10:04 UTC, GodsDusk commented on python/lab-array-attributes-and-dtype/verify3.sh
> +cat ~/.python_history | grep "dtype="
要考虑用户多打了空格的情况

2023-04-10 03:37 UTC, GodsDusk approved these changes

2023-04-12 02:09 UTC, huhuhang approved these changes

2023-04-12 02:18 UTC, merged