add challenge-linear-algebra-solving-with-numpy
labex-labs/scenarios pull request #329
Opened 2023-04-05 15:32 UTC by Xuwx37

# PR Checklist

- fix #175 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-04-06 01:03 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/step2.md
> +Write a Python function `svd_matrix(matrix)` that takes a NumPy matrix as input and performs Singular Value Decomposition (SVD) on the matrix. The function should return three matrices: U, S, and V.
数学符号用 \$ 包起来 $U$ , $S$, and $V$.

2023-04-06 01:04 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/step1.md
> +- Completing `invert_matrix.py`
下同

2023-04-06 01:06 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/assets/svd_matrix_test.py
> +    A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
测试用例最好不要和example用的一样

2023-04-06 01:12 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/assets/svd_matrix_test.py
> +def test_svd_matrix(self):
检测脚本有问题，无操作都能通过，自己再把所有的都测一遍

2023-04-06 01:13 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/step2.md
> +Write a Python function `svd_matrix(matrix)` that takes a NumPy matrix as input and performs Singular Value Decomposition (SVD) on the matrix. The function should return three matrices: U, S, and V.
下同

2023-04-06 01:14 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/step4.md
> +- If A.shape[0] is not equal to A.shape[1] or A.shape[0] is not equal to b.shape[0], the dimensions of matrix A and matrix b do not match, the function should raise a `ValueError` with an appropriate
`A.shape[0]`

2023-04-06 01:16 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/index.json
> +  "description": "In this challenge, you are tasked with writing a Python program that utilizes the NumPy and Linear Algebra libraries to perform matrix inversion.",
不要照抄intro，再精简一点

2023-04-07 01:06 UTC, GodsDusk requested changes

2023-04-07 01:06 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/step1.md
> +## Example Input
每个step要一致，要么没有example output，要么都加上，同时output的形式也要统一

2023-04-07 01:10 UTC, huhuhang requested changes

2023-04-07 01:10 UTC, huhuhang commented on python/challenge-linear-algebra-solving-with-numpy/index.json
需要将 solutions 绑定到 step。参考：https://www.labex.wiki/zh/basic/how-to-start#indexjson

2023-04-10 01:05 UTC, GodsDusk requested changes

2023-04-10 01:05 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/index.json
> +  "difficulty": "Intermediate",
感觉难度也不高，改成初级吧

2023-04-14 02:32 UTC, GodsDusk requested changes

2023-04-14 02:32 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/step1.md
> +print("invert_A:\n",invert_matrix(A))
用格式化工具格式格式化一遍，`,` 后面肯定是有空格的，另外的也检查一下

2023-04-14 02:34 UTC, Xuwx37 commented on python/challenge-linear-algebra-solving-with-numpy/step1.md
> +print("invert_A:\n",invert_matrix(A))
格式化了，我的文件没有改变

2023-04-14 03:39 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/step1.md
> +print("invert_A:\n",invert_matrix(A))
> 格式化了，我的文件没有改变

用 Prettier 没法直接对markdown 里的 code block 格式化，这种要单独复制出来处理

2023-04-14 03:46 UTC, Xuwx37 commented on python/challenge-linear-algebra-solving-with-numpy/step1.md
> +print("invert_A:\n",invert_matrix(A))
单独复制了，也没有变化，不知`,`后面的空格是什么呢？

2023-04-14 03:46 UTC, Xuwx37 commented on python/challenge-linear-algebra-solving-with-numpy/step1.md
> +print("invert_A:\n",invert_matrix(A))
在`,`后面没有打空格

2023-04-14 05:51 UTC, GodsDusk commented on python/challenge-linear-algebra-solving-with-numpy/step1.md
> +print("invert_A:\n",invert_matrix(A))
> 单独复制了，也没有变化，不知`,`后面的空格是什么呢？

按照 python pep8 的标准， `,` 后面要接一个空格，如下是正确格式：

```
print("invert_A:\n", invert_matrix(A)) # 注意 , 后面的空格，你的文件里没有
```

2023-04-14 06:54 UTC, GodsDusk approved these changes

2023-04-17 01:18 UTC, huhuhang approved these changes

2023-04-17 01:18 UTC, merged