challenge-docker-image-registry
labex-labs/scenarios pull request #332
Opened 2023-04-06 08:15 UTC by xinxin68

# PR Checklist

- fix #28 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-04-11 07:42 UTC, joker-bai commented on docker/challenge-docker-image-registry/index.json
> +    "imageid": "webide-instance-ubuntu:2204"
这个项目用vnc-ubuntu:2204镜像应该就可以。

2023-04-11 07:42 UTC, joker-bai commented on docker/challenge-docker-image-registry/intro.md
> +## Skills
将该地方的Skills删掉，不需要写在这里

2023-04-11 07:42 UTC, joker-bai commented on docker/challenge-docker-image-registry/setup.sh
> +#!/bin/zsh
这个地方删除，这里都做了，后面都不需要用户操作了。

2023-04-11 07:42 UTC, joker-bai commented on docker/challenge-docker-image-registry/step3.md
> +
这里太简单了，建议分成两部：
1、启动端口为5000的服务
2、登录服务

2023-04-11 07:42 UTC, joker-bai commented on docker/challenge-docker-image-registry/step4.md
> +- Understand the `Docker run` command is to create a container and run it on the local machine using an image.
命令应该是`docker run`

2023-04-11 07:42 UTC, joker-bai commented on docker/challenge-docker-image-registry/verify1.sh
> +if [ "$(docker images | grep ' ubuntu:20.04' | grep 'ubuntu:tag')" ]; then
你的step1只是把ubuntu:20.04镜像拉取下来，怎么会检测到ubuntu:tag标签的镜像呢

2023-04-11 07:42 UTC, joker-bai commented on docker/challenge-docker-image-registry/verify1.sh
> +
现在不需要做什么操作，检测脚本都能过。我们希望的是在用户未进行操作的时候检测脚本是不通过的，只有用户按照提示进行操作了，检测脚本才能通过。下面的检测脚本有同样的问题

2023-04-11 07:42 UTC, joker-bai commented on docker/challenge-docker-image-registry/step1.md
> +
建议增加截图，然用户知道他做的效果你的期望效果是一致的。下同

2023-04-11 07:42 UTC, joker-bai commented on docker/challenge-docker-image-registry/solutions/SOLUTIONS.md
> +
将solutions按步骤进行拆分，并且在index.json中进行绑定，可以参考https://www.labex.wiki/zh/basic/how-to-start#indexjson 或者 https://github.com/labex-labs/scenarios/blob/master/docker/challenge-docker-image-and-registry/index.json

2023-04-13 01:38 UTC, joker-bai requested changes

2023-04-13 01:38 UTC, joker-bai commented on docker/challenge-docker-image-registry/index.json
> +        "solutions": ["step1-solution.md"]
这里的名字和你本来的名字不一致。你原名是step1-solutions.md，多了一个s

2023-04-13 01:38 UTC, joker-bai commented on docker/challenge-docker-image-registry/index.json
> +    "imageid": "vnc-ubuntu:2204"
不好意思，这里换成vnc-instance-ubuntu:2204吧

2023-04-17 04:44 UTC, huhuhang commented
Hi, @mercury7720 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review

2023-04-18 02:26 UTC, joker-bai requested changes

2023-04-18 02:26 UTC, joker-bai commented on docker/challenge-docker-image-registry/index.json
> +  "title": "Using docker commands to  perform common tasks.",
issue的题目好像是：Docker Image and Resigtry

2023-04-18 02:26 UTC, joker-bai commented on docker/challenge-docker-image-registry/intro.md
> +# Docker Operation Command
这里也要改Docker Image and Resigtry

2023-04-18 02:26 UTC, joker-bai commented on docker/challenge-docker-image-registry/step1.md
> +# Challenge pull docker image.
根据标题的规则进行修改https://labex-docs.vercel.app/zh/basic/formatting-guide

2023-04-18 02:26 UTC, joker-bai commented on docker/challenge-docker-image-registry/step2.md
> +# Challenge apply a custom name to a image.
根据标题的规则进行修改https://labex-docs.vercel.app/zh/basic/formatting-guide

2023-04-18 02:26 UTC, joker-bai commented on docker/challenge-docker-image-registry/step3.md
> +# Challenge login a Docker registry.
根据标题的规则进行修改https://labex-docs.vercel.app/zh/basic/formatting-guide

2023-04-18 02:26 UTC, joker-bai commented on docker/challenge-docker-image-registry/step4.md
> +# Challenge run a container.
根据标题的规则进行修改https://labex-docs.vercel.app/zh/basic/formatting-guide

2023-04-20 07:34 UTC, joker-bai requested changes

2023-04-20 07:34 UTC, joker-bai commented on docker/challenge-docker-image-registry/verify1.sh
> +docker images | grep 'ubuntu:20.04'
使用docker images 查看的镜像信息如下：
```
labex:~/ $ docker images 
REPOSITORY                    TAG       IMAGE ID       CREATED        SIZE
ubuntu                        20.04     88bd68917189   6 days ago     72.8MB
```
所以你上面的检测方式是无法检测通过的。

2023-04-20 07:34 UTC, joker-bai commented on docker/challenge-docker-image-registry/step4.md
> +- Successfully upload the tagged image to the localhost:5000 private repository.
我没猜错的话，这里的逻辑应该是：
1、把ubuntu:tag的地址改成localhost:5000/ubuntu:tag
2、把镜像推到私有仓库
3、使用私有镜像启动容器

目前的逻辑有点不清晰，用户分不清到底应该怎么操作。我们应该把用户当成小白。

2023-04-20 07:34 UTC, joker-bai commented on docker/challenge-docker-image-registry/finish.md
> +In this challenge, you will learn how to use Docker commands to perform common tasks such as pulling the ubuntu:20.04 image, tagging it, logging in to the localhost:5000 Docker registry, pushing the
将镜像以及自定义的关键字用单反引号括起来，比如ubuntu:20.04，localhost:5000。下面有类似的都一并修改了。

2023-04-21 09:05 UTC, closed without merging