Challenge git branch operation
labex-labs/scenarios pull request #345
Opened 2023-04-07 07:51 UTC by xinxin68

# PR Checklist

- fix #95 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-04-11 10:55 UTC, joker-bai requested changes

2023-04-11 10:55 UTC, joker-bai commented on linux/challenge-git-branch-operation/solutions/SOLUTIONS.md
> +
把solutions按步骤进行拆分，然后在`index.json`中进行绑定

2023-04-11 10:55 UTC, joker-bai commented on linux/challenge-git-branch-operation/step1.md
> +Challenge: Create a new branch using the branch command.
注意文档格式，第一行应该是Title。

2023-04-11 10:55 UTC, joker-bai commented on linux/challenge-git-branch-operation/step1.md
> +
这里应该新增一个clone代码并进入代码目录的操作，用户无法在一个非git目录中创建分支

2023-04-11 10:55 UTC, joker-bai commented on linux/challenge-git-branch-operation/verify1.sh
> +cd /home/labex/.oh-my-zsh/plugins/vscode
进入这个目录的理由是什么？如果本步骤是在该仓库下执行，在step1中就应该先进入这个目录。

2023-04-11 10:55 UTC, joker-bai commented on linux/challenge-git-branch-operation/step2.md
> +
应该新增一个切换到new-branch分支的步骤

2023-04-11 10:55 UTC, joker-bai commented on linux/challenge-git-branch-operation/verify2.sh
> +diff=$(git diff --name-only origin/$current_branch)
脚本检测不过

2023-04-11 10:55 UTC, joker-bai commented on linux/challenge-git-branch-operation/verify3.sh
> +if [ "$1" != "$current_branch" ]; then
这个$1从哪里来？

2023-04-11 10:55 UTC, joker-bai commented on linux/challenge-git-branch-operation/verify4.sh
> +#!/bin/zsh
这个脚本未做任何操作都能检测过

2023-04-11 10:55 UTC, joker-bai commented on linux/challenge-git-branch-operation/index.json
> +        "skills": ["git/branch"],
增加solution校验

2023-04-17 04:44 UTC, huhuhang commented
Hi, @mercury7720 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review

2023-04-17 05:05 UTC, huhuhang commented
> Hi, @mercury7720
> 
> 由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。
> 
> * Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review

已经重新分配给 @joker-bai

2023-04-20 01:37 UTC, joker-bai commented
@huhuhang 这个建议重做

2023-04-20 02:47 UTC, closed without merging