Challenge pipeline and redirection
labex-labs/scenarios pull request #346
Opened 2023-04-07 08:07 UTC by xinxin68

# PR Checklist

- fix #34 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-04-17 18:23 UTC, huhuhang commented
Hi, @mercury7720 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review 

如有疑问可以直接回复本条评论，或者微信联系。

2023-04-18 02:15 UTC, joker-bai requested changes

2023-04-18 02:15 UTC, joker-bai commented on linux/challenge-pipeline-and-redirection/index.json
> +    "imageid": "webide-ubuntu:2004"
镜像用：webide-ubuntu:2204

2023-04-18 02:18 UTC, joker-bai requested changes

2023-04-18 02:18 UTC, joker-bai commented on linux/challenge-pipeline-and-redirection/intro.md
> +# Docker Operation Command
这个标题好像和内容不符合

2023-04-18 02:18 UTC, joker-bai commented on linux/challenge-pipeline-and-redirection/step1.md
> +```
建议用格式化插件格式化一下

2023-04-18 02:18 UTC, joker-bai commented on linux/challenge-pipeline-and-redirection/step3.md
> +```
格式化一下

2023-04-20 07:42 UTC, joker-bai requested changes

2023-04-20 07:42 UTC, joker-bai commented on linux/challenge-pipeline-and-redirection/intro.md
> +# Docker Operation Command
这个标题和本次实验不符合

2023-04-20 07:42 UTC, joker-bai commented on linux/challenge-pipeline-and-redirection/verify1.sh
> +Num=`wc -l example.txt | cut -d ' ' -f1`
脚本检测不过，你应该进入/home/project目录

2023-04-20 07:42 UTC, joker-bai commented on linux/challenge-pipeline-and-redirection/verify2.sh
> +RES=`cat output.txt`
这里一样需要先进入目录

2023-04-20 07:42 UTC, joker-bai commented on linux/challenge-pipeline-and-redirection/verify3.sh
> +sudo cat example/file1.txt >> example/file2.txt
需要先进入目录

2023-04-20 07:42 UTC, joker-bai commented on linux/challenge-pipeline-and-redirection/index.json
> +  "title": "Challenge logical, redirect and pipline command.",
这里的标题和期望的好像不符https://github.com/labex-labs/scenarios/issues/34

2023-04-23 00:42 UTC, huhuhang commented
超期关闭

2023-04-23 00:42 UTC, closed without merging