add python/challenge-find-expressions
labex-labs/scenarios pull request #350
Opened 2023-04-08 05:43 UTC by CALMorACT

# PR Checklist

- fix #35

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-04-08 06:00 UTC, CALMorACT commented
@huhuhang finish test

2023-04-11 07:30 UTC, huhuhang requested changes
整体还不错。👍

2023-04-11 07:30 UTC, huhuhang commented on python/challenge-find-expressions/intro.md
> +**The order of the integers in the expressions does no matter**(`2+4`==`4+2`, Don't appear twice).
markdown 换行，段落之间有空行。否则会渲染成一段。

2023-04-11 07:30 UTC, huhuhang commented on python/challenge-find-expressions/index.json
> +        "solution": ["find_expressions.py"]
绑定有问题，solutions

2023-04-11 07:30 UTC, huhuhang commented on python/challenge-find-expressions/index.json
> +        "solution": ["find_expressions.py"]
所有用户端未通过时，没有显示 solution 的提示。

2023-04-11 08:55 UTC, CALMorACT commented on python/challenge-find-expressions/intro.md
> +**The order of the integers in the expressions does no matter**(`2+4`==`4+2`, Don't appear twice).
已经修复，加粗后忘记换行了

2023-04-11 08:55 UTC, CALMorACT commented on python/challenge-find-expressions/index.json
> +        "solution": ["find_expressions.py"]
已经修复，给 solutions 也加了 solution.md，之前测试时候没测到

2023-04-12 03:38 UTC, huhuhang approved these changes

2023-04-12 03:38 UTC, merged

2023-04-17 04:44 UTC, huhuhang commented
Hi, @huhuhang 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review