Add lab python assignment and reference
labex-labs/scenarios pull request #356
Opened 2023-04-09 10:52 UTC by AsukaLove2

# PR Checklist

- fix #270 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-04-09 11:12 UTC, AsukaLove2 commented
@GodsDusk 老师，测试好了，麻烦你检查一下

2023-04-10 01:21 UTC, GodsDusk requested changes

2023-04-10 01:21 UTC, GodsDusk commented on python/lab-python-assignment-and-reference/verify3-0.sh
> +cat ~/.python_history | grep "append(4)"
step2中已经有 append(4) 了，这里再用这个检测就直接通过了

2023-04-10 01:21 UTC, GodsDusk commented on python/lab-python-assignment-and-reference/step3.md
> +print("immutable_string:", immutable_string)
这个例子也没完全说明 Immutable，应该把 another_immutable_string 也打印出来

2023-04-10 01:21 UTC, GodsDusk commented on python/lab-python-assignment-and-reference/step4.md
> +def append_to_list(item: int, a_list: list = None) -> list:
这个例子想说明什么？
而且你没有在环境里运行过这个例子吧

2023-04-10 01:21 UTC, GodsDusk commented on python/lab-python-assignment-and-reference/step4.md
> +## Copying mutable objects
copy 可以单独拆成一个step

2023-04-10 01:21 UTC, GodsDusk commented on python/lab-python-assignment-and-reference/step4.md
> +For nested mutable objects, use the `deepcopy` function from the `copy` module:
为什么nested mutable objects需要deepcopy？建议在同一个实验中体现出copy和deepcopy的差异

2023-04-10 02:20 UTC, closed without merging