Add challenge-complete-a-json-parser
labex-labs/scenarios pull request #386
Opened 2023-04-12 08:55 UTC by Ternence001

# PR Checklist

- fix #ID

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-04-12 09:57 UTC, Ternence001 commented
@huhuhang 线上测试完成。

2023-04-12 12:05 UTC, Ternence001 commented
@huhuhang 线上测试完成。

2023-04-13 02:08 UTC, huhuhang commented
> # PR Checklist
> * fix [challenge-complete-a-json-parser #232](https://github.com/labex-labs/scenarios/issues/232)
> 
> 请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。
> 
> 请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。
> 
> Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.
> 
> Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

@Ternence001 这里是绑定 issue 的 ID 而不是这个 PR 的 ID，我已经修改，后续请注意。

2023-04-13 02:12 UTC, huhuhang requested changes
问题很严重，无法进行 Review，应该未理解 challenge 的概念和处理方法。请重新观看视频并模仿已完成的 challenge 的 issue 和 PR。

链接：https://lusun.com/v/y8QaSCBgC37
密码：virX

2023-04-13 02:12 UTC, huhuhang commented on python/challenge-complete-a-json-parser/intro.md
> +# Json Parser
JSON

2023-04-14 07:07 UTC, Ternence001 commented
Test Completed

2023-04-17 01:57 UTC, huhuhang commented
![CleanShot 2023-04-17 at 09 56 08](https://user-images.githubusercontent.com/5147530/232359913-ec91c4ee-cd2d-4a1d-9a29-ceff99f88893.png)

@Ternence001 step1 并没有说明不让用 JSON，此外对 JSON 包使用的检测应该放在最开始。

2023-04-17 04:43 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review

2023-04-17 06:13 UTC, Ternence001 commented
@huhuhang 已全部修正。等待核验。

2023-04-17 06:36 UTC, huhuhang commented
需要 @GodsDusk Review。

2023-04-17 08:39 UTC, GodsDusk commented
@Ternence001 确认没问题后通知我review

2023-04-17 09:22 UTC, Ternence001 commented
@GodsDusk 确认无误，申请review。

2023-04-18 01:11 UTC, GodsDusk requested changes

2023-04-18 01:11 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/index.json
> +    "imageid": "vnc-ubuntu:2204"
文件操作的使用webide环境

2023-04-18 01:11 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/solutions/parse_json.md
> +# Solution
无用文件，要么你把这个拆到 .py 中，要么就删了，下同

2023-04-18 01:11 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/assets/json_lib_test2.py
> +from serialize_json import *
这边最好加个 importerror 的检测

2023-04-18 01:11 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/step2.md
> +```json
格式beautiful一下

2023-04-18 05:04 UTC, Ternence001 commented
@GodsDusk 申请再次review。
已无大问题，测试过程都一切正常了，也能够检测出是否没有按照要求导入了json库，以及程序功能是否正确的检测。关于“加个 importerror 的检测”这句建议不太明白具体要检测什么问题。
![image](https://user-images.githubusercontent.com/98000140/232676150-db243a42-563e-4d10-b5a8-41376e349fc6.png)

2023-04-18 05:51 UTC, GodsDusk requested changes

2023-04-18 05:51 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/step2.md
> +```
建议格式：
'{
    "name": "John",
    "age": 30,
    "city": "New York",
    "isEmployed": true,
    "car": null,
    "grades": [
        90,
        85,
        95
    ]
}'

2023-04-18 05:51 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/index.json
> +            "showstderr": false
这边设为 true 就行，如果用户脚本有问题，导致 import error，那你用false显示的就是你的 hint，用户会觉得摸不着头脑

2023-04-18 05:51 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/step1.md
> +You are given a string that represents a JSON object, write a Python function that can parse the string and return the corresponding Python object. In addition, you are not allowed to use the json li
要么 `json` library，要么大写

2023-04-18 05:51 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/step1.md
> +```json
同理，不要写在一行，跟output一样形式美化一下

2023-04-18 05:51 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/step1.md
> +## TODO
TODO 写在开头阅读体验不好
还不如
write a Python function in ...py that

下同

2023-04-18 05:51 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/step1.md
> +- String
要么不写括号内容，不然都要吧，而且要用代码符号括起来 String (`str`)

2023-04-18 08:22 UTC, GodsDusk requested changes

2023-04-18 08:22 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/step1.md
> +- String
> 要么不写括号内容，不然都要吧，而且要用代码符号括起来 String (`str`)

没改完啊。。

- String (`str`)
- Null (`None`)

2023-04-18 08:22 UTC, GodsDusk commented on python/challenge-complete-a-json-parser/step1.md
> +Please complete the file `/home/labex/project/parse_json.py`.
确认这个描述顺序符合阅读习惯吗，确认的话我也不要求你改了 😂

2023-04-18 08:52 UTC, Ternence001 commented on python/challenge-complete-a-json-parser/step1.md
> +Please complete the file `/home/labex/project/parse_json.py`.
不好意思，我又修改了下。感谢指出。😂

2023-04-19 01:05 UTC, GodsDusk approved these changes

2023-04-19 02:18 UTC, huhuhang requested changes
还是有很多细节问题。

2023-04-19 02:18 UTC, huhuhang commented on python/challenge-complete-a-json-parser/step1.md
> +- String('str')
? 格式漏了？

2023-04-19 02:18 UTC, huhuhang commented on python/challenge-complete-a-json-parser/step1.md
> +```
代码块都需要有语法标记

2023-04-19 02:18 UTC, huhuhang commented on python/challenge-complete-a-json-parser/step1.md
> +```python
正确的语法标记

2023-04-19 02:18 UTC, huhuhang commented on python/challenge-complete-a-json-parser/step2.md
> +- Null('None')
格式

2023-04-19 02:18 UTC, huhuhang commented on python/challenge-complete-a-json-parser/intro.md
> +# Complete A JSON Parser
Complete a JSON Parser

我们用的是 Title Case 的 AP 样式，可以用这个转换器：https://titlecaseconverter.com/

2023-04-19 02:18 UTC, huhuhang commented on python/challenge-complete-a-json-parser/index.json
> +  "title": "JSON Parser",
多个地方的标题要统一。md 里面的，这里的 title，文件夹名称等。

2023-04-20 01:25 UTC, Ternence001 commented
@huhuhang

2023-04-20 03:14 UTC, Ternence001 commented
@huhuhang

2023-04-20 08:06 UTC, huhuhang approved these changes

2023-04-20 08:07 UTC, merged