add: lab-docker-lifecycle-management
labex-labs/scenarios pull request #394
Opened 2023-04-12 14:27 UTC by zhangdongdong7

# PR Checklist

- fix #335

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-04-13 15:12 UTC, zhangdongdong7 commented
Test Completed

2023-04-13 15:17 UTC, zhangdongdong7 commented
@huhuhang done，帮忙Reviewer一下，我没办法选择和打lable。

2023-04-14 01:48 UTC, joker-bai requested changes
请按照提示做相应的修改

2023-04-14 01:48 UTC, joker-bai commented on docker/lab-docker-lifecycle-management/step1.md
> +1. Create a new directory and navigate into it.
改成：Create a new directory called `/home/labex/docker` and navigate into it.  这样用户才会有一个明确的目标

2023-04-14 01:48 UTC, joker-bai commented on docker/lab-docker-lifecycle-management/verify1-1.sh
> +ls |grep Dockerfile
假如我创建的目录是 /home/labex/docker，在这个下面创建了Dockerfile，你这个检测脚本是不被通过的。要明确目录，明确文件，比如 ls /home/labex/docker | grep Dockerfile 或者 test -f /home/labex/docker/Dockerfile，其他检测脚本类似问题

2023-04-14 01:48 UTC, joker-bai commented on docker/lab-docker-lifecycle-management/step1.md
> +```
加上代码块属性，比如 ```html，其他类型。后续我在做issue的时候会主动添加，如果没有添加的麻烦自己添加一下。

2023-04-14 01:48 UTC, joker-bai commented on docker/lab-docker-lifecycle-management/verify3-1.sh
> +cat ~/.zsh_history |grep "stop"
还是需要稍微严谨一点，比如 cat ~/.zsh_history |grep docker |grep "stop"，下同

2023-04-14 16:05 UTC, zhangdongdong7 commented
@joker-bai done

2023-04-15 05:39 UTC, joker-bai requested changes

2023-04-15 11:32 UTC, zhangdongdong7 commented
@joker-bai done，Please review，tks

2023-04-15 12:20 UTC, joker-bai approved these changes

2023-04-15 12:20 UTC, joker-bai commented
@huhuhang 请再次Check

2023-04-17 02:39 UTC, huhuhang requested changes

2023-04-17 02:39 UTC, huhuhang commented on docker/lab-docker-lifecycle-management/step1.md
> +1. Create a new directory called /home/labex/docker-demo and navigate into it.
代码、路径、文件名等都需要用 markdown 单反引号的行内代码样式。

2023-04-17 02:39 UTC, huhuhang commented on docker/lab-docker-lifecycle-management/step1.md
> +cd /home/labex/docker-demo
不要使用 demo，test 等这类不规范的名称做示例。

比如这里可以叫 simple image，hello docker 之类的。详见 https://www.labex.wiki/zh/basic/formatting-guide#%E4%BB%A3%E7%A0%81

2023-04-17 03:23 UTC, zhangdongdong7 commented
@huhuhang hi,已修改

2023-04-17 04:43 UTC, huhuhang commented
Hi, @joker-bai 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review

2023-04-17 06:03 UTC, joker-bai approved these changes

2023-04-17 06:26 UTC, huhuhang approved these changes

2023-04-17 06:27 UTC, merged