Lab accessing and managing docker container
labex-labs/scenarios pull request #396
Opened 2023-04-13 01:54 UTC by xiachengfan

# PR Checklist

- fix #336 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

2023-04-13 07:10 UTC, xiachengfan commented
Test Completed

2023-04-13 07:10 UTC, xiachengfan commented
@joker-bai

2023-04-13 07:43 UTC, joker-bai requested changes

2023-04-13 07:43 UTC, joker-bai commented on docker/lab-accessing-and-managing-docker-container/verify4.sh
> +docker ps -a |grep my-shell-container || echo "ok"
检测脚本有问题，操作与否都为真

2023-04-13 08:24 UTC, joker-bai approved these changes

2023-04-13 09:54 UTC, huhuhang requested changes

2023-04-13 09:54 UTC, huhuhang commented on docker/lab-accessing-and-managing-docker-container/index.json
> +          }
这里绑定了 logs skills，没有对 docker logs my-container 是否执行的检测。可以通过获取 zsh 历史记录检测。

2023-04-13 09:54 UTC, huhuhang commented on docker/lab-accessing-and-managing-docker-container/verify4.sh
> +fi
不操作也可以直接 PASS

2023-04-13 09:54 UTC, huhuhang commented on docker/lab-accessing-and-managing-docker-container/finish.md
> +# Conclusion
Summary

2023-04-14 01:33 UTC, joker-bai approved these changes

2023-04-14 07:01 UTC, huhuhang approved these changes

2023-04-14 07:02 UTC, merged

2023-04-17 04:43 UTC, huhuhang commented
Hi, @joker-bai 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review