Add challenge-find-the-flags
labex-labs/scenarios pull request #403
Opened 2023-04-13 03:37 UTC by thenicebro

# PR Checklist

- fix #389 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-14 02:29 UTC, Shuchong-LI requested changes
主要问题是按照solution无法找到最初的file1导致无法pass，此外注意文本格式的准确与统一。

2023-04-14 02:29 UTC, Shuchong-LI commented on linux/challenge-find-the-flags/step1.md
> +### Introduction
1.从一级标题开始 # 
2.删掉Step 1:

2023-04-14 02:29 UTC, Shuchong-LI commented on linux/challenge-find-the-flags/step1.md
> +```
在测试环境中有不正常的代码高亮，尝试使用```text ``` 或者 ```plaintext ``` 取消掉代码高亮。

2023-04-14 02:29 UTC, Shuchong-LI commented on linux/challenge-find-the-flags/step1.md
> +- You should be able to find the first flag file in the current directory using the cat command.
cat 使用反引号``

2023-04-14 02:29 UTC, Shuchong-LI commented on linux/challenge-find-the-flags/solutions/step1-solution.md
flag的序号不相符
![Screenshot from 2023-04-14 10-14-50](https://user-images.githubusercontent.com/63344346/231924886-1e93c68e-9736-44af-a027-5f0998e3d307.png)

2023-04-14 04:39 UTC, Shuchong-LI requested changes
关于pro的solution部分注意仔细检查。

2023-04-14 04:39 UTC, Shuchong-LI commented on linux/challenge-find-the-flags/solutions/step4-solution.md
> +- Input `mv flag4.txt ~/resolve` command to move this file to the specified location.
cd到/tmp之后需要引导用户回到～目录下，或者直接删掉第一步cd /tmp

2023-04-17 02:47 UTC, huhuhang approved these changes

2023-04-17 02:48 UTC, merged

2023-04-17 04:43 UTC, huhuhang commented
Hi, @thenicebro 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review