Challenge count duplicates
labex-labs/scenarios pull request #407
Opened 2023-04-13 03:57 UTC by Liugaga-vvv

# PR Checklist

- fix #387

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-14 03:36 UTC, Shuchong-LI requested changes
整体没有太大问题，注意一下英文内容的输出。

2023-04-14 03:36 UTC, Shuchong-LI commented on python/challenge-count-duplicates/intro.md
intro部分是为用户介绍一下这个挑战中用到的知识点，最好能够给出几个应用场景。不要把具体的挑战内容放在intro里，单调且与后面step的内容重复。

2023-04-14 03:36 UTC, Shuchong-LI commented on python/challenge-count-duplicates/step1.md
> +- Completing `count_duplicates.py`
Complete，包括index里title和hint里面的句首动词最好都不加ing。

2023-04-14 03:36 UTC, Shuchong-LI commented on python/challenge-count-duplicates/step1.md
> +2. The function should return an integer value which represents the count of characters in the string that appear more than once.
用无序列表

2023-04-14 03:36 UTC, Shuchong-LI commented on python/challenge-count-duplicates/finish.md
不要在summary里给出解决方案，而是要总结一下用到的相关知识点。
这里的内容完全可以放到solution里面以注释的形式给到用户。

2023-04-14 09:13 UTC, Liugaga-vvv commented on python/challenge-count-duplicates/finish.md
这部分内容和step1里面的内容也重复，我觉得放在solution里面也没意义 所以直接删除了

2023-04-15 07:52 UTC, Shuchong-LI reviewed
没有问题了，等待merge

2023-04-17 04:43 UTC, huhuhang commented
Hi, @jiaosenvip 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review

2023-04-17 07:56 UTC, Shuchong-LI approved these changes

2023-04-18 02:21 UTC, huhuhang approved these changes

2023-04-18 02:21 UTC, merged