Add challenge local and global scope
labex-labs/scenarios pull request #431
Opened 2023-04-13 10:33 UTC by Beichen-Ma

# PR Checklist

- fix #420 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-14 04:14 UTC, Shuchong-LI requested changes
主要问题是solutions的用户端显示出错。关于pro功能一定要仔细检查确保没有问题，毕竟人家是花钱买的。相同问题注意全部修改。

2023-04-14 04:14 UTC, Shuchong-LI commented on python/challenge-local-and-global-scope/step2.md
> +6. Finally, call the `inner_function` from the `outer_function`.
这里为用户标好了序号，那么在step1中也要使用相同的格式。注意风格统一。

2023-04-14 04:14 UTC, Shuchong-LI commented on python/challenge-local-and-global-scope/solutions/step2.py
格式乱码
![image](https://user-images.githubusercontent.com/63344346/231938460-5726ca24-5bb5-4dd5-8804-acfffafb6dcd.png)

2023-04-14 04:14 UTC, Shuchong-LI commented on python/challenge-local-and-global-scope/index.json
> +                        "name": "Test the implement of step1.py",
implementation

2023-04-14 07:46 UTC, Beichen-Ma commented
> 

solution渲染时的bug，不是制作内容时的错误。

2023-04-14 11:10 UTC, Beichen-Ma commented
@Shuchong-LI  major repair改下？

2023-04-17 04:43 UTC, huhuhang commented
Hi, @Beichen-Ma 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review

2023-04-17 05:47 UTC, huhuhang commented
Hi, @huhuhang 

系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review 

如有疑问可以直接回复本条评论，或者微信联系。

2023-04-17 05:52 UTC, huhuhang commented
该 PR 已经人工分配给 @Shuchong-LI 处理。

2023-04-18 02:14 UTC, huhuhang approved these changes

2023-04-18 02:14 UTC, merged