add lab-webbrowser-package-basic
labex-labs/scenarios pull request #433
Opened 2023-04-13 11:50 UTC by Aixiiba

# PR Checklist

- fix #385 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-17 04:42 UTC, huhuhang commented
Hi, @Shuchong-LI 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review

2023-04-17 08:27 UTC, Shuchong-LI requested changes
做得很好，整体没有问题，注意相关python package 以及相关函数名需要用反引号引用。

2023-04-17 08:27 UTC, Shuchong-LI commented on python/lab-webbrowser-package-basic/intro.md
> +The webbrowser module in Python provides a simple interface to open web browsers, display HTML documents, and navigate the web. This practical lab will walk you through the basics of using the webbro
正文中webbroeser字样用反引号引用

2023-04-17 08:27 UTC, Shuchong-LI commented on python/lab-webbrowser-package-basic/intro.md
> +- Python Interpreter
skills部分删除

2023-04-17 08:27 UTC, Shuchong-LI commented on python/lab-webbrowser-package-basic/step1.md
同样正文webbrowser以及open_new_tab() 这个函数用反引号引用，所有步骤相关问题注意全部修改。

2023-04-17 08:55 UTC, Aixiiba commented on python/lab-webbrowser-package-basic/step1.md
好的，正在修复提交pr

2023-04-21 11:57 UTC, Shuchong-LI approved these changes

2023-04-23 00:52 UTC, huhuhang approved these changes

2023-04-23 00:53 UTC, merged