Add lab custom docker images
labex-labs/scenarios pull request #457
Opened 2023-04-14 12:53 UTC by GuoJiang-yw

# PR Checklist

- fix #339 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-18 02:43 UTC, joker-bai requested changes

2023-04-18 02:43 UTC, joker-bai commented on docker/lab-custom-docker-images/verify1-2.sh
> +echo -e "<!DOCTYPE html>\n<html>\n<head>\n	<title>Hello Docker!</title>\n</head>\n<body>\n	<h1>Hello Docker!</h1>\n</body>\n</html>" > /home/labex/index1_output.html
这里检测不过，建议直接检测文件是否存在以及文本里的关键字即可

2023-04-18 02:43 UTC, joker-bai commented on docker/lab-custom-docker-images/step2.md
> +RUN echo "daemon off;" >> /etc/nginx/nginx.conf
把`RUN echo "daemon off;" >> /etc/nginx/nginx.conf`删掉（我的问题，题出的不严谨）。

2023-04-18 02:43 UTC, joker-bai commented on docker/lab-custom-docker-images/step2.md
> +docker run -it my-nginx-curl bash
把这里改成`docker run -d --name curl my-nginx-curl`

2023-04-18 02:43 UTC, joker-bai commented on docker/lab-custom-docker-images/step2.md
> +```bash
在这个代码块中增加一句：`docker exec -it curl bash`

2023-04-18 02:43 UTC, joker-bai commented on docker/lab-custom-docker-images/verify2-1.sh
> +echo -e 'FROM nginx\nRUN apt-get update && apt-get install -y curl\nCOPY index.html /usr/share/nginx/html/\nRUN echo "daemon off;" >> /etc/nginx/nginx.conf' > /home/labex/Dockerfile2_output
这个检测脚本和上面index.html一样的问题

2023-04-18 02:43 UTC, joker-bai commented on docker/lab-custom-docker-images/verify2-2.sh
> +echo -e "<!DOCTYPE html>\n<html>\n<head>\n	<title>Hello Docker!</title>\n</head>\n<body>\n	<h1>Hello Docker!</h1>\n</body>\n</html>" > /home/labex/index2_output.html
这里也换一种检测方式

2023-04-18 02:43 UTC, joker-bai commented on docker/lab-custom-docker-images/verify3-1.sh
> +echo -e 'FROM nginx\nENV NGINX_PORT 8080\nRUN sed -i "s/listen\s*80;/listen $NGINX_PORT;/g" /etc/nginx/conf.d/default.conf\nCOPY index.html /usr/share/nginx/html/' > /home/labex/Dockerfile3_output
这里一样

2023-04-18 02:43 UTC, joker-bai commented on docker/lab-custom-docker-images/verify3-2.sh
> +echo -e "<!DOCTYPE html>\n<html>\n<head>\n	<title>Hello Docker!</title>\n</head>\n<body>\n	<h1>Hello Docker!</h1>\n</body>\n</html>" > /home/labex/index3_output.html
这里一样

2023-04-18 06:07 UTC, joker-bai requested changes

2023-04-18 06:07 UTC, joker-bai commented on docker/lab-custom-docker-images/verify2-4.sh
> +docker ps -a | grep my-nginx-curl
再检测一下后面那个步骤吧，也就是docker exec命令

2023-04-18 06:38 UTC, joker-bai approved these changes
@huhuhang

2023-04-19 01:44 UTC, huhuhang approved these changes

2023-04-19 01:44 UTC, merged