Challenge voting system
labex-labs/scenarios pull request #467
Opened 2023-04-17 03:25 UTC by Liugaga-vvv

# PR Checklist

- fix #459 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-17 04:27 UTC, huhuhang commented
Hi, @jiaosenvip 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。
 Review 标准：https://www.labex.wiki/zh/advanced/how-to-review

2023-04-17 04:29 UTC, huhuhang commented
Hi, @jiaosenvip 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review

2023-04-17 04:37 UTC, jiaosenvip approved these changes

2023-04-17 04:41 UTC, huhuhang commented
Hi, @jiaosenvip 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

- Review 操作指南和标准详见：https://www.labex.wiki/zh/advanced/how-to-review

2023-04-17 05:03 UTC, huhuhang requested changes

2023-04-17 05:03 UTC, huhuhang commented on python/challenge-voting-system/finish.md
> +- Overall, this task provides a practical example of how to solve a real-world problem using Python programming.
列表中间没有空行。

2023-04-17 05:03 UTC, huhuhang commented on python/challenge-voting-system/finish.md
> +- Overall, this task provides a practical example of how to solve a real-world problem using Python programming.
最后一句不应该放入列表中？

2023-04-17 05:03 UTC, huhuhang commented on python/challenge-voting-system/solutions/calculate_winner.py
> +        return winner[0].capitalize()
solutions 最好有注释，可以由 ChatGPT 写好，确认一下即可。

2023-04-17 05:03 UTC, huhuhang commented on python/challenge-voting-system/solutions/calculate_winner.py
> +        return winner[0].capitalize()
![CleanShot 2023-04-17 at 13 02 26](https://user-images.githubusercontent.com/5147530/232383067-ae10f77e-efdc-4eeb-a26b-7e43009c3ea8.png)

2023-04-17 05:03 UTC, huhuhang commented on python/challenge-voting-system/solutions/calculate_winner.py
> +        return winner[0].capitalize()
需要确认和更新：

```py
# This function takes a list of votes as input and returns the winner
def calculate_winner(votes):
    # Initialize an empty dictionary to store the vote counts
    vote_count = {}

    # Iterate through each vote in the input list
    for vote in votes:
        # Convert the vote to lowercase to handle case-insensitive inputs
        vote = vote.lower()

        # Check if the vote already exists in the vote_count dictionary
        if vote in vote_count:
            # If it does, increment the vote count by 1
            vote_count[vote] += 1
        else:
            # If it doesn't, add the vote to the dictionary with a count of 1
            vote_count[vote] = 1

    # Find the maximum vote count from the dictionary values
    max_count = max(vote_count.values())

    # Get a list of all the candidates with the maximum vote count
    winner = [key for key, value in vote_count.items() if value == max_count]

    # If there is a tie between multiple candidates, return "Tie"
    if len(winner) > 1:
        return "Tie"
    # Otherwise, return the winner in title case
    else:
        return winner[0].capitalize()
```

2023-04-17 05:04 UTC, huhuhang commented
@Liugaga-vvv @jiaosenvip 二次 Review 完成，请知悉。

2023-04-18 00:59 UTC, huhuhang approved these changes

2023-04-18 00:59 UTC, merged