add opencv/lab-getting-started-with-images
labex-labs/scenarios pull request #479
Opened 2023-04-17 09:23 UTC by CALMorACT

# PR Checklist

- fix #434

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-18 01:30 UTC, GodsDusk requested changes

2023-04-18 01:30 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/intro.md
> +This tutorial will teach us the basics of working with images using the OpenCV-Python library. By the end of this tutorial, you will be able to read, display, and save images.
teach you

2023-04-18 01:30 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step1.md
> +# Step 1 Import the required libraries
不需要 Step 1 这种前缀，下同

2023-04-18 01:30 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step1.md
> +First, let's import the required libraries. We will use the `cv2` library for image processing.
这边的检测有点莫名其妙，在哪import? 另外这是一个lab，不是challenge，可以对用户宽容一点

2023-04-18 01:30 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step1.md
> +First, let's import the required libraries. We will use the `cv2` library for image processing.
下面的问题也放在这里说了，
1. 我觉得这个lab不用创建文件在文件中操作，直接打开终端操作就行了，图片放桌面
2. 这是一个lab，不是challenge，lab针对的是完全没有学过opencv的小白，不要用challenge的方法去考察用户，建议参考一下master中别的lab是怎么写的

2023-04-18 04:04 UTC, CALMorACT commented on opencv/lab-getting-started-with-images/step1.md
> +First, let's import the required libraries. We will use the `cv2` library for image processing.
> 这边的检测有点莫名其妙，在哪import? 另外这是一个lab，不是challenge，可以对用户宽容一点

import 检测我目前检测 cv2.__version__ 可以看一下 import_opencv_test.py，当然遵循你的建议我会改成检测 python history

2023-04-18 05:55 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step1.md
> +First, let's import the required libraries. We will use the `cv2` library for image processing.
> > 这边的检测有点莫名其妙，在哪import? 另外这是一个lab，不是challenge，可以对用户宽容一点
> 
> import 检测我目前检测 `cv2.__version__` 可以看一下 import_opencv_test.py，当然遵循你的建议我会改成检测 python history.

我的意思是从用户的角度来看，在文中你都没让我做任何事情（let's import the required libraries 在哪import？终端？文件？文件在哪？），但忽然就来了一个检测，至少让用户干什么要说清楚

2023-04-18 07:03 UTC, GodsDusk commented
还有就是确认一下你的图片来源，需要是 CC0 的无版权图片，或者用 skimage.data 中自带的图片

2023-04-18 07:23 UTC, CALMorACT commented
> 还有就是确认一下你的图片来源，需要是 CC0 的无版权图片，或者用 skimage.data 中自带的图片
这个我专门找了个cc0无版权图片的网站来着

2023-04-18 07:23 UTC, CALMorACT commented on opencv/lab-getting-started-with-images/step1.md
> +First, let's import the required libraries. We will use the `cv2` library for image processing.
> > > 这边的检测有点莫名其妙，在哪import? 另外这是一个lab，不是challenge，可以对用户宽容一点
> > 
> > 
> > import 检测我目前检测 `cv2.__version__` 可以看一下 import_opencv_test.py，当然遵循你的建议我会改成检测 python history.
> 
> 我的意思是从用户的角度来看，在文中你都没让我做任何事情（let's import the required libraries 在哪import？终端？文件？文件在哪？），但忽然就来了一个检测，至少让用户干什么要说清楚

可以，我大体明白lab的流程了，偏“学习”，所以检测不会很严格

2023-04-18 07:59 UTC, CALMorACT commented
@GodsDusk 可以重新 review 一下，改的差不多

2023-04-18 08:39 UTC, GodsDusk requested changes

2023-04-18 08:39 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step1.md
> +## Example
Example 这个二级标题的描述不太合适，考虑换个称呼，或者直接去掉了

2023-04-18 08:39 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step1.md
> +Input `python` to start the process of python interpreter. Then input the following code.
输入python命令前要引导用户打开桌面的终端，并进入python环境

2023-04-18 08:39 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step2.md
> +import cv2
不需要重复 import

2023-04-18 08:39 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step2.md
> +Image path is `/tmp/Image.jpg`
路径不要放 /tmp ，桌面或者默认路径都行

2023-04-18 08:39 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step4.md
> +image = cv2.imread('/tmp/Image.jpg')
路径同上

2023-04-18 08:39 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step4.md
> +To save an image in a different format, we use the cv2.imwrite() function. The function takes two arguments: the file path and the image to save.
注意代码 we use the `cv2.imwrite()` function

2023-04-18 08:39 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/index.json
> +        "skills": ["opencv/imshow", "opencv/wait_key"]
用到了 destroyAllWindows 就要写上，skill tree 里没有，觉得有必要的话就联系管理员加上

2023-04-18 10:42 UTC, CALMorACT commented on opencv/lab-getting-started-with-images/step1.md
> +## Example
intro 里面写了

2023-04-18 10:42 UTC, CALMorACT commented on opencv/lab-getting-started-with-images/step1.md
> +Input `python` to start the process of python interpreter. Then input the following code.
intro 里面写了

2023-04-18 10:45 UTC, CALMorACT commented on opencv/lab-getting-started-with-images/step2.md
> +Image path is `/tmp/Image.jpg`
这个有什么评价方式吗，我看到大部分在 assets 里的内容会放在 /tmp 中

2023-04-18 10:50 UTC, CALMorACT commented on opencv/lab-getting-started-with-images/index.json
> +        "skills": ["opencv/imshow", "opencv/wait_key"]
应当是需要 destroyAllWindow 的，良好的代码风格就应该有，而我们 lab 直接用的解释器，不加这个不会结束窗口

2023-04-18 10:55 UTC, CALMorACT commented on opencv/lab-getting-started-with-images/step1.md
> +## Example
code detail如何

2023-04-18 11:04 UTC, CALMorACT commented on opencv/lab-getting-started-with-images/step2.md
> +import cv2
好的，请问lab中串联步骤的重叠代码都不要重复是吧

2023-04-19 01:37 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step1.md
> +## Example
> code detail如何

去掉 code吧，因为不仅是code，还有operate

2023-04-19 01:38 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step1.md
> +Input `python` to start the process of python interpreter. Then input the following code.
> intro 里面写了

写了不够啊，还要给出具体的操作步骤，这里也可以检测一下用户是否进入了python环境，注意intro里不要给操作步骤，都放step里

2023-04-19 01:38 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step2.md
> +import cv2
> 好的，请问lab中串联步骤的重叠代码都不要重复是吧

对，step 与 step 之间环境不会有任何变化

2023-04-19 01:39 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step2.md
> +Image path is `/tmp/Image.jpg`
> 这个有什么评价方式吗，我看到大部分在 assets 里的内容会放在 /tmp 中

只有检测脚本放 /tmp

2023-04-19 01:39 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/index.json
> +        "skills": ["opencv/imshow", "opencv/wait_key"]
> 应当是需要 destroyAllWindow 的，良好的代码风格就应该有（destroy window 的操作本身就是和 imshow 一同出现的，应该都属于 imshow 的 skills tree，当然另外加也可以），而我们 lab 直接用的解释器，不destroy不会结束窗口
> 
> 如果衡量觉得要加的话，你可以加一下吗？（我不清楚管理员是哪几位）

已经加到 skill tree 里了

2023-04-19 03:29 UTC, CALMorACT commented on opencv/lab-getting-started-with-images/step1.md
> +Input `python` to start the process of python interpreter. Then input the following code.
那是不是我应该新增一步专门去描述怎么打开桌面怎么进入终端，还需要截个图
另外，这是不是也应该算做一个skill？如果不算，加个步骤感觉没意义

2023-04-19 03:55 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step1.md
> +Input `python` to start the process of python interpreter. Then input the following code.
> 详细步骤，我应该新增一步专门去描述怎么打开桌面怎么进入终端，还需要截个图 另外，这是不是也应该算做一个skill？如果不算，加个步骤感觉没意义 此外基于我们 skill 是一个递进的过程，这个操作是不是应该设计成一个 lab 让用户去熟悉 vnc 环境会更好一些
> 
> 检测进入 python 环境的话，我目前直接检测 python_history，如果不存在 import 字段就会异常，这也就顺带检测了有没有进入python环境，还是这个观点，我寻思这种基础性操作是不是应该新做一个lab让用户熟悉环境

简单说明即可，比如 https://github.com/labex-labs/scenarios/blob/master/numpy/lab-numpy-file-io/step1.md#open-the-python-shell

2023-04-19 10:09 UTC, CALMorACT commented on opencv/lab-getting-started-with-images/step1.md
> +Input `python` to start the process of python interpreter. Then input the following code.
> > 详细步骤，我应该新增一步专门去描述怎么打开桌面怎么进入终端，还需要截个图 另外，这是不是也应该算做一个skill？如果不算，加个步骤感觉没意义 此外基于我们 skill 是一个递进的过程，这个操作是不是应该设计成一个 lab 让用户去熟悉 vnc 环境会更好一些
> > 检测进入 python 环境的话，我目前直接检测 python_history，如果不存在 import 字段就会异常，这也就顺带检测了有没有进入python环境，还是这个观点，我寻思这种基础性操作是不是应该新做一个lab让用户熟悉环境
> 
> 简单说明即可，比如 https://github.com/labex-labs/scenarios/blob/master/numpy/lab-numpy-file-io/step1.md#open-the-python-shell

okok

2023-04-19 11:11 UTC, CALMorACT commented
@GodsDusk 辛苦老哥再 review 一下，上面提的问题都解决了

2023-04-20 01:27 UTC, GodsDusk requested changes
最后几个小问题

2023-04-20 01:27 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step1.md
> +Input `python` to start the process of python interpreter. Then input the following code.
上下要一致，上面是 `python3`，而且这个描述应该放步骤的上面吧，建议改为

Start the process of python interpreter.

```bash
python3
```

Then input the following code to import OpenCV-Python package.

2023-04-20 01:27 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step4.md
> +1. In this case, we save the image **in the PNG format** (Image.png). The image is saved **in the same directory** (/tmp) as the Python script.
(/tmp) 没改

2023-04-20 01:27 UTC, GodsDusk commented on opencv/lab-getting-started-with-images/step3.md
> +# Display the image, image has been loaded in step 2
用户看不到自己是 step 几，换种描述吧

2023-04-20 04:19 UTC, CALMorACT commented
大概是没有问题了，辛苦reviewer的付出！

2023-04-20 05:54 UTC, GodsDusk approved these changes
我这没问题了

推荐你认领 #247
可以用你最早提交的方式来做 @CALMorACT

2023-04-21 02:53 UTC, huhuhang approved these changes

2023-04-21 02:53 UTC, merged

2023-04-21 06:29 UTC, CALMorACT commented
> 我这没问题了
> 
> 推荐你认领 #247 可以用你最早提交的方式来做 @CALMorACT

在赶毕业论文，下周试试