add-challenge-numpy-array-datatype-converter
labex-labs/scenarios pull request #504
Opened 2023-04-18 10:17 UTC by Beichen-Ma

# PR Checklist

- fix #495

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-18 14:10 UTC, huhuhang commented
Hi, @huhuhang 

系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。

[❓ 如何 Review](https://www.labex.wiki/zh/advanced/how-to-review) | [✍️ LabEx 手册](https://www.labex.wiki/zh/advanced/how-to-review) | [🏪 LabEx 网站](https://labex.io) 

> 这是一条自动消息，如有疑问可以直接回复本条评论，或者微信联系。

2023-04-19 01:49 UTC, huhuhang requested changes

2023-04-19 01:49 UTC, huhuhang commented on numpy/challenge-numpy-array-datatype-converter/intro.md
> +Numpy is a powerful library for scientific computing in Python. One of the features of numpy is its ability to efficiently work with arrays. However, sometimes it is necessary to convert a list of in
NumPy

2023-04-23 02:40 UTC, huhuhang commented
为啥只改了我批注的那一处，不能搜索看一下有没有类似的问题吗？

2023-04-26 02:58 UTC, Xuwx37 commented on numpy/challenge-numpy-array-datatype-converter/index.json
> +                ],
还有numpy/array

2023-04-26 03:00 UTC, Xuwx37 commented on numpy/challenge-numpy-array-datatype-converter/index.json
> +    "description": "In this challenge, you will be required to write a Python function that converts a list of integers into a numpy array with a specified datatype. This will test your understanding
可以再简短一些

2023-04-26 03:02 UTC, Xuwx37 requested changes

2023-04-26 03:02 UTC, Xuwx37 commented on numpy/challenge-numpy-array-datatype-converter/index.json
> +    "description": "In this challenge, you will be required to write a Python function that converts a list of integers into a numpy array with a specified datatype. This will test your understanding
可以再简短一些

2023-04-26 03:02 UTC, Xuwx37 commented on numpy/challenge-numpy-array-datatype-converter/index.json
> +                    "python/function_basic"
还有numpy/array

2023-04-26 03:12 UTC, huhuhang approved these changes

2023-04-26 03:12 UTC, merged