提交文件操作计权限挑战
labex-labs/scenarios pull request #55
Opened 2023-02-19 01:38 UTC by LJJ931026

# PR Checklist

Please post the link to the PR-related issue here (请将 PR 相关的 issues 的链接贴于此处):

Please make sure you've completed the relevant tasks for this PR from the following list (请确保完成下方检查项，提交后打勾):

- [x] The structure of the lab/challenge is correct.(实验/挑战的结构正确)
- [x] The format of the lab/challenge is correct.(实验/挑战的格式正确)
- [x] The code and verification scripts have been tested in the environment.(代码和验证脚本在环境中测试通过)
- [x] I promise that I have not plagiarised and have not copied the solution from other sources, AIGC is not included.(我保证没有抄袭，也没有从其他来源复制解决方案，AIGC 不包括在内)

See the [Contribution Guidelines](https://labex-docs.vercel.app/) for more details.(请参阅 [贡献指南](https://labex-docs.vercel.app/) 了解更多信息。)

2023-02-20 13:54 UTC, LJJ931026 commented on linux/challenge-file-properties/intro.md
> +In this challange, you will use `ls` command to list the files and it's properties in specified directory.
已修改

2023-02-20 13:55 UTC, LJJ931026 commented on linux/challenge-file-properties/step3.md
> +![challenge-file-properties-3-3](./assets/challenge-file-properties-3-3.png)
已删除

2023-03-08 13:31 UTC, LJJ931026 commented on linux/challenge-file-properties/index.json
> +  "time": "5 minutes",
已修改

2023-03-08 13:31 UTC, LJJ931026 commented on linux/challenge-file-properties/index.json
> +    "imageid": "ubuntu:2004"
已修改

2023-03-08 13:32 UTC, LJJ931026 commented on linux/challenge-file-properties/index.json
> +  "description": "Linux basic operation command to create files and file properties.",
已优化

2023-03-08 13:32 UTC, LJJ931026 commented on linux/challenge-file-properties/step4.md
> +- Change the file owner to `shiyanlou`.
之前的环境有该用户所以用的，现在还有其他用户吗？还是需要创建一个新用户？

2023-04-03 09:24 UTC, huhuhang requested changes

2023-04-03 09:24 UTC, huhuhang commented on linux/challenge-file-properties/solutions/SOLUTIONS.md
需要将 solutions 拆分一下，绑定到 step。参考：https://www.labex.wiki/zh/basic/how-to-start#indexjson

2023-04-03 09:24 UTC, huhuhang commented on linux/challenge-file-properties/step4.md
> +- Change the file owner to `shiyanlou`.
这个问题需要在 2204 环境中确认一下。如果没有的话，可以 setup 脚本创建一个用户。但最好是不用 shiyanlou，老外看不懂。

2023-04-07 07:16 UTC, merged

2023-04-07 07:17 UTC, huhuhang commented
作者放弃修改，交由 LabEx 修改后合并。

2023-04-17 04:47 UTC, huhuhang commented
Hi, @LJJ931026 

该 PR 未检测到正确关联 Issue，请你在 PR 描述中按要求添加，如有问题请及时联系 LabEx 的同事。