Add challenge-count-the-vowels
labex-labs/scenarios pull request #570
Opened 2023-04-21 09:38 UTC by AsukaLove2

# PR Checklist

- fix #383 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-25 01:40 UTC, jiaosenvip commented on python/challenge-count-the-vowels/finish.md
> +In this challenge, you were tasked with creating a Python function that counts the number of vowels in a given string. You were able to use your knowledge of string manipulation and Python functions
这一段内容修改一下，替换成下面内容。

```md
Through the challenge of creating a function to count vowels in a string, we learned about functions, parameters, strings, loops, conditionals, and the importance of counting and iterating through strings in programming. This exercise provided a practical application of these concepts.
```

2023-04-25 01:46 UTC, jiaosenvip commented on python/challenge-count-the-vowels/index.json
> +  "title": "Count the vowels",
`Count the Vowels` 注意标题书写

2023-04-25 01:50 UTC, jiaosenvip commented on python/challenge-count-the-vowels/step1.md
> +
Requirements 前面增加 TODO

```
## TODO

To complete `count_vowels.py`.
```

2023-04-25 01:51 UTC, jiaosenvip requested changes
注意标题大小写，增加TODO，修改总结。

2023-04-26 04:06 UTC, jiaosenvip approved these changes

2023-04-27 00:45 UTC, huhuhang approved these changes

2023-04-27 00:46 UTC, merged