Add challenge-play-images-with-color-spaces
labex-labs/scenarios pull request #572
Opened 2023-04-21 12:26 UTC by Ternence001

# PR Checklist

- fix #533 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-21 14:03 UTC, GodsDusk requested changes
检查一下你的pr，怎么把别人的文件也提交上来了，另外无关的编译文件不要提交

先这样改吧，明后天我再看下实验流程

2023-04-21 14:09 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

[❓ 如何 Review](https://www.labex.wiki/zh/advanced/how-to-review) | [✍️ LabEx 手册](https://www.labex.wiki/zh/advanced/how-to-review) | [🏪 LabEx 网站](https://labex.io) 

> 这是一条自动消息，如有疑问可以直接回复本条评论，或者微信联系。

2023-04-23 00:29 UTC, huhuhang commented
![CleanShot 2023-04-23 at 08 29 16](https://user-images.githubusercontent.com/5147530/233813059-4bdd5476-8a83-45e0-bca6-3699a15b826d.png)

@Ternence001 PR 有大量冲突，此外不要给 PR 添加除 Test Completed 以外的标签。

2023-04-23 01:30 UTC, GodsDusk requested changes

2023-04-23 01:30 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/solutions/convert_color_space.py
> +# 保存图像
不要有中文

2023-04-23 01:30 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/step1.md
> +And we provide an image file `images/img1.jpg` for you to test.
确认一下图片的版权？

2023-04-23 01:30 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/solutions/detect_color.py
> +    print(hsv_image)
多余了

2023-04-23 01:30 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/solutions/detect_color.py
> +import numpy as np
没用到就不需要 import

2023-04-23 01:30 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/assets/detect_color_test.py
> +        image_path = '/home/labex/project/images/img1.jpg'
不要用同一张图片测试

2023-04-23 01:30 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/assets/convert_color_space_test.py
> +        image_path = '/home/labex/project/images/img1.jpg'
不要用同一张图片测试

2023-04-23 01:30 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/assets/detect_color_test.py
> +        self.assertEqual(blue_masked_image.shape, image.shape)
和上面一样，最好有对像素的 assertEqual 之类的判断

2023-04-23 01:30 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/step1.md
> +- First you need to install the `opencv-python` library from the command line with the following command:
后续会内置在环境里，这一步可以不用

2023-04-23 03:57 UTC, Ternence001 commented
@GodsDusk 已按要求整改。确认使用图片无版权问题，为个人亲手拍摄。import numpy as np并非没有用到，在定义函数的设置传入参数环节，删除后会报错。其余部分已均按要求整改，并再次经过线上测试。

2023-04-23 06:21 UTC, GodsDusk requested changes

2023-04-23 06:21 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/intro.md
> +In this challenge, you will work with `OpenCV-Python` to create an application that demonstrates various color space transformations and image manipulations. This challenge is designed for individual
OpenCV-Python 这种写法不需要代码括起来，`opencv-python` 才需要

2023-04-23 06:21 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/index.json
> +                        "showstderr": false
能设为 true 的尽量用 true

2023-04-23 06:21 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/step2.md
> +- Display the original image and the masked image.
这里的 display 没改

2023-04-23 06:21 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/step2.md
> +4. Display the masked image.
没改

2023-04-23 10:14 UTC, GodsDusk requested changes

2023-04-23 10:14 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/assets/convert_color_space.py
> +# 保存图像
这里没改，再对照一下之前的review，全过一遍

2023-04-23 11:33 UTC, GodsDusk requested changes
最后一个小问题

2023-04-23 11:33 UTC, GodsDusk commented on python/challenge-play-images-with-color-spaces/index.json
> +    "description": "In this challenge, you will implement functions on color space Transformations and Color-based Object Detection.",
注意大小写

2023-04-23 11:38 UTC, GodsDusk approved these changes

2023-04-23 11:44 UTC, Ternence001 commented
@huhuhang

2023-04-24 01:17 UTC, huhuhang approved these changes

2023-04-24 01:17 UTC, merged