challenge-template-matching-and-drawing-results
labex-labs/scenarios pull request #600
Opened 2023-04-24 11:16 UTC by Ternence001

# PR Checklist

- fix #569 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-24 11:57 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

[❓ 如何 Review](https://www.labex.wiki/zh/advanced/how-to-review) | [✍️ LabEx 手册](https://www.labex.wiki/zh/advanced/how-to-review) | [🏪 LabEx 网站](https://labex.io) 

> 这是一条自动消息，如有疑问可以直接回复本条评论，或者微信联系。

2023-04-24 14:32 UTC, GodsDusk requested changes
所有检测脚本的假阳性都太高了，感觉体验不好，有可能用户没怎么操作就通过了，
1. 加强一下检测脚本的严格程度
2. 如果不改检测脚本的话至少在桌面上给出用户自测用例的答案

以上任选一个

2023-04-24 14:32 UTC, GodsDusk commented on opencv/challenge-template-matching-and-drawing-results/step1.md
> +You can use the images `"test_source.jpg"` and `"test_template.jpg"` for testing.
`"test_source.jpg"` `"test_template.jpg"` 不属于代码块
另外附一下图片的来源

2023-04-24 14:32 UTC, GodsDusk commented on opencv/challenge-template-matching-and-drawing-results/index.json
> +  "description": "In this challenge, participants are tasked with implementing template matching in OpenCV and visualize the results.",
不要照抄intro，再短点

2023-04-24 14:32 UTC, GodsDusk commented on opencv/challenge-template-matching-and-drawing-results/index.json
> +            "showstderr": false
true

2023-04-24 14:32 UTC, GodsDusk commented on opencv/challenge-template-matching-and-drawing-results/assets/draw_rectangles_around_matches.py
> +# path1 = "gray_source.jpg"
path 和环境路径文件名一致

2023-04-24 14:32 UTC, GodsDusk commented on opencv/challenge-template-matching-and-drawing-results/solutions/perform_template_matching.py
> +        result = cv2.matchTemplate(gray_source, gray_template, eval(method))
不建议用 eval，改用字典形式

2023-04-24 14:32 UTC, GodsDusk commented on opencv/challenge-template-matching-and-drawing-results/assets/perform_template_matching.py
> +# print(best_matches)
给用户一个输出样例

2023-04-25 01:50 UTC, Ternence001 commented
@GodsDusk 
已按要求整改。
加强了三个脚本的检测强度，具体方法是确保了输出结果的唯一性，然后要求输出结果完全相等。并经过测试，方案可行；
图片来源暂未附加，因图片由个人使用PPT制作出，不涉及版权问题。如需附加，还请指示具体细节；
已缩减introduction；
已改false为true；
已修改相关文件路径，并经过测试，可行（包括注释代码中的路径）；
已不再使用eval()，而改为字典；
已分别提供输出示例。

2023-04-25 02:49 UTC, GodsDusk requested changes

2023-04-25 02:49 UTC, GodsDusk commented on opencv/challenge-template-matching-and-drawing-results/assets/test_perform_template_matching.py
> +        self.assertEqual(best_matches, best_matches2)
equal 其实太强了，如果用户在 matchTemplate 前做了个 blur，也不能说用户做错了吧，可能跟答案差几个像素，建议用范围判断

2023-04-25 02:49 UTC, GodsDusk commented on opencv/challenge-template-matching-and-drawing-results/assets/test_draw_rectangles_around_matches.py
> +        self.assertEqual((result['cv2.TM_SQDIFF_NORMED'] != result2['cv2.TM_SQDIFF_NORMED']).sum(), 0)
这个判断也有问题，你并没有告诉用户 rectangle 时需要的参数，完全像素相等肯定不对 ：`cv2.rectangle(source_image.copy(), top_left3, bottom_right3, colors[method3], 3)` 就通不过了，更别说加了别的参数

我觉得应该判断不想等+部分区域相等即可

2023-04-25 06:18 UTC, Ternence001 commented
@GodsDusk 
已对检测方式加以修改，现行具体方案如下：
对load_and_convert_images()函数，因答案唯一，故不做修改，继续使用完全相等检测。

对perform_template_matching()函数，检测其是否使用了"cv2.matchTemplate"方法，输出结果是否是字典，输出字典的键值对个数是否为3，三种method是否都在字典的键中，输出字典键值对的values(元组)的lenghts是否为2，以及该元组的第二个值(表示坐标)是否长度也为2。总的相当于是检测了输出结果的格式。{str:(a,(b,c))}

对draw_rectangles_around_matches()函数, 首先检测是否使用了"cv2.rectangle"。然后检测输出结果是否是字典，长度是否为3，每种方法是否是字典的键。每种方法对应的数组的shape是否等于原图像。最后检测每种方法绘制矩形，矩形的颜色(a,b,c)是否在输出的图像中。（在就表示draw过了）。

2023-04-26 01:40 UTC, GodsDusk requested changes

2023-04-26 01:40 UTC, GodsDusk commented on opencv/challenge-template-matching-and-drawing-results/assets/test_draw_rectangles_around_matches.py
> +        colors = {'cv2.TM_SQDIFF_NORMED': (0, 255, 0), 'cv2.TM_CCOEFF_NORMED': (255, 0, 0), 'cv2.TM_CCORR_NORMED': (0, 0, 255)}
最好说明一下要用户选择这些我们指定的颜色

2023-04-26 01:40 UTC, GodsDusk commented on opencv/challenge-template-matching-and-drawing-results/assets/test_draw_rectangles_around_matches.py
> +            self.assertIn(list(colors[m]), result[m].reshape(-1,3).tolist())
这边会有点问题，如果我用了不同的颜色，提交检测后，系统直接超时了
![WX20230426-093738@2x](https://user-images.githubusercontent.com/13726533/234443880-e040d320-1a10-457d-a140-f7ac0c1a3823.png)
原因是unittest 在断言时会把所有像素输出到终端导致检测脚本超时，试试用 set(colors[m]) 会不会这样，或者检测手段再简单点

2023-04-26 05:23 UTC, Ternence001 commented
@GodsDusk 
已增加颜色需求。
已降低检测强度，将颜色在图片中的判断改为了，图像不等于原图像的判断。

2023-04-26 06:03 UTC, GodsDusk approved these changes

2023-04-26 06:15 UTC, Ternence001 commented
@huhuhang

2023-04-27 00:44 UTC, huhuhang approved these changes

2023-04-27 00:44 UTC, merged