challenge-morphological-transformationsMorphological transformations
labex-labs/scenarios pull request #612
Opened 2023-04-25 09:31 UTC by Ternence001

# PR Checklist

- fix #584 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-25 10:09 UTC, Ternence001 commented
该项目的检测方法：
检测了要求使用的函数工具是否有被使用。以及结果的类型，shape，以及是否相比原image在像素上有变化。如果既使用了要求的方法，又使图像像素发生了变化，且输出的类型是数组，则判断为正确，允许pass。

2023-04-25 14:07 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

[❓ 如何 Review](https://www.labex.wiki/zh/advanced/how-to-review) | [✍️ LabEx 手册](https://www.labex.wiki/zh/advanced/how-to-review) | [🏪 LabEx 网站](https://labex.io) 

> 这是一条自动消息，如有疑问可以直接回复本条评论，或者微信联系。

2023-04-26 02:06 UTC, GodsDusk requested changes

2023-04-26 02:06 UTC, GodsDusk commented on opencv/challenge-morphological-transformations/step3.md
> +- Use different structuring elements (e.g., rectangular, elliptical, cross-shaped) and sizes.
(e.g.,

2023-04-26 08:20 UTC, Ternence001 commented
@GodsDusk 
已按要求修改。
对每个step都添加了图片对照。并修改了相关文本语法问题。
description已修改。
除此之外，关于技能树中有关numpy的技能，step1中使用了np.zeros()方法，但是此方法不在技能树中。除此之外没有直接使用其他numpy方法，所以没有添加相关技能。

2023-04-26 08:49 UTC, GodsDusk requested changes

2023-04-26 08:49 UTC, GodsDusk commented on opencv/challenge-morphological-transformations/step2.md
> +Take `apply_dilation_and_erosion(image, "cross", 5, 3,3)` as an example to process the target binary image.
这边格式不对，逗号后少了个空格 `apply_dilation_and_erosion(image, "cross", 5, 3, 3)`

2023-04-26 08:49 UTC, GodsDusk commented on opencv/challenge-morphological-transformations/step2.md
> +Take `apply_dilation_and_erosion(image, "cross", 5, 3,3)` as an example to process the target binary image.
下面也是，再通篇检查一下

2023-04-26 08:49 UTC, GodsDusk commented on opencv/challenge-morphological-transformations/solutions/generate_binary_image.py
> +    image = np.zeros((height, width), dtype=np.uint8)
其实应该算在 numpy/array 里，因为image的数据结构就是这个

2023-04-26 08:49 UTC, GodsDusk commented on opencv/challenge-morphological-transformations/solutions/generate_binary_image.py
> +            center = (random.randint(0, width - 1), random.randint(0, height - 1))
另外就是为了让用户没有前置知识点的遗漏，尽量覆盖，把random改为 np.random， 然后在 index 里加上

2023-04-26 09:12 UTC, Ternence001 commented
@GodsDusk 已按要求修改。

2023-04-26 09:52 UTC, GodsDusk approved these changes

2023-04-26 10:52 UTC, Ternence001 commented
@huhuhang

2023-04-27 00:41 UTC, huhuhang approved these changes

2023-04-27 00:41 UTC, merged