challenge-find-edgesFind edges
labex-labs/scenarios pull request #622
Opened 2023-04-26 11:53 UTC by Ternence001

# PR Checklist

- fix #548 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-27 04:33 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

[❓ 如何 Review](https://www.labex.wiki/zh/advanced/how-to-review) | [✍️ LabEx 手册](https://www.labex.wiki/zh/advanced/how-to-review) | [🏪 LabEx 网站](https://labex.io) 

> 这是一条自动消息，如有疑问可以直接回复本条评论，或者微信联系。

2023-04-27 07:27 UTC, GodsDusk requested changes

2023-04-27 07:27 UTC, GodsDusk commented on opencv/challenge-find-edges/finish.md
> +In this advanced Python programming challenge, you have successfully implemented an edge detection application using the OpenCV library. By completing this challenge, you have demonstrated your abili
这是个beginner，把全篇的 advanced 去了

2023-04-27 07:27 UTC, GodsDusk commented on opencv/challenge-find-edges/setup.sh
> +#!/bin/zsh
和主编确定了，opencv-python 要在启动时给用户装了，同时要把版本号带上避免以后有问题。

你另外几个已经merge的也改一下，单独提交一个pr给主编审核就行

2023-04-27 07:27 UTC, GodsDusk commented on opencv/challenge-find-edges/index.json
> +    "time": 15,
15 分钟应该完不成吧，这个也要注意修改

2023-04-27 07:27 UTC, GodsDusk commented on opencv/challenge-find-edges/step1.md
> +3. Apply Gaussian Blur to the grayscale image using the OpenCV `cv2.GaussianBlur()` function, with a kernel size of 5x5.
应该是 with a default kernel size of 5x5

2023-04-27 07:27 UTC, GodsDusk commented on opencv/challenge-find-edges/step1.md
> +## Introduction
这个二级标题可以都不用

2023-04-27 07:27 UTC, GodsDusk commented on opencv/challenge-find-edges/step2.md
> +Please complete the `apply_edge_detection` function in the file `/home/labex/project/apply_edge_detection.py`.
这句怎么跑最上面了，要跟前面的格式一致吧

2023-04-27 07:27 UTC, GodsDusk commented on opencv/challenge-find-edges/step2.md
> +In Laplacian of Gaussian (LoG) edge detection, the image is first Laplacian filtered with the parameter ddepth as cv2.CV_64F. Then the image is binarized according to the Laplace filtering result, s
行内代码也要括起来 `cv2.CV_64F`

2023-04-27 07:27 UTC, GodsDusk commented on opencv/challenge-find-edges/step2.md
> +3. Display the original image, Canny edge detection result, and the LoG result side by side for comparison.
没有 display 吧

2023-04-27 07:27 UTC, GodsDusk commented on opencv/challenge-find-edges/step2.md
> +In Canny edge detection, the parameter threshold1 is 20, and the parameter threshold2 is 120.
threshold1 threshold2 太不规范，用 lower 之类

2023-04-27 07:27 UTC, GodsDusk commented on opencv/challenge-find-edges/assets/apply_edge_detection.py
> +
给用户的文件有问题，跟solution比较一下缺什么

2023-04-27 07:27 UTC, GodsDusk commented on opencv/challenge-find-edges/step3.md
> +combined_edge s= fine_tune_and_save_result(image, canny_edges_img, log_edges_img,"combined_edge_image.jpg")
combined_edge s  多了空格

2023-04-27 10:28 UTC, Ternence001 commented
@GodsDusk 已按要求修改并测试。

2023-04-28 00:57 UTC, GodsDusk approved these changes

2023-04-28 04:04 UTC, Ternence001 commented
@huhuhang

2023-05-04 00:54 UTC, merged