lab-getting-started-with-videos
labex-labs/scenarios pull request #626
Opened 2023-04-27 04:32 UTC by huduo0812

# PR Checklist

- fix #512

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-27 07:32 UTC, huduo0812 commented
test completed

2023-04-27 11:11 UTC, GodsDusk requested changes

2023-04-27 11:11 UTC, GodsDusk commented on opencv/lab-getting-started-with-videos/index.json
> +    "imageid": "vnc-ubuntu:2204"
issue里说了，用webide环境，把imshow改为imwrite体验会更好

2023-04-27 13:16 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

[❓ 如何 Review](https://www.labex.wiki/zh/advanced/how-to-review) | [✍️ LabEx 手册](https://www.labex.wiki/zh/advanced/how-to-review) | [🏪 LabEx 网站](https://labex.io) 

> 这是一条自动消息，如有疑问可以直接回复本条评论，或者微信联系。

2023-04-28 05:37 UTC, GodsDusk requested changes

2023-04-28 05:37 UTC, GodsDusk commented on opencv/lab-getting-started-with-videos/step1.md
> +Video path is `/home/labex/Desktop/video.mp4`
webide 默认路径是 /home/labex/project，要注意

2023-04-28 05:37 UTC, GodsDusk commented on opencv/lab-getting-started-with-videos/step1.md
> +Input `python` to start the process of python interpreter. Then input the following code.
改用文件让用户实现吧，在终端输这么长的命令体验不好，同下

2023-04-28 07:28 UTC, GodsDusk requested changes
最后两个问题，改完就approve了

2023-04-28 07:28 UTC, GodsDusk commented on opencv/lab-getting-started-with-videos/step1.md
> +        cv2.imwrite('save.jpg', frame)
保存一张不够吧，建议还是创建一个文件夹，然后把每一帧都输出到这个文件夹里

2023-04-28 08:50 UTC, GodsDusk requested changes

2023-04-28 08:50 UTC, GodsDusk commented on opencv/lab-getting-started-with-videos/step1.md
> +        cv2.imwrite('./frame/save' + str(number) + '.jpg', frame)
用f-string

2023-04-28 08:50 UTC, GodsDusk commented on opencv/lab-getting-started-with-videos/step1.md
> +	print "new folder..."
用py3的print()

2023-04-28 08:50 UTC, GodsDusk commented on opencv/lab-getting-started-with-videos/step1.md
> +import os
有 os 的话 index.json 中相关 skill 也要加上

2023-04-28 09:49 UTC, GodsDusk requested changes

2023-04-28 09:49 UTC, GodsDusk commented on opencv/lab-getting-started-with-videos/step1.md
> +	print ('new folder...')
多余的空格，要遵守 pep8

2023-04-28 09:49 UTC, GodsDusk commented on opencv/lab-getting-started-with-videos/step1.md
> +    number = str(number)
也没必要str()啊，f-string自己就能转

2023-04-29 10:23 UTC, GodsDusk requested changes

2023-04-29 10:23 UTC, GodsDusk commented on opencv/lab-getting-started-with-videos/step1.md
> +	print ('new folder...')
还是没改
`print ('new folder...')`
`print('new folder...')`

制作手册里有格式检验插件，用插件把代码都格式化一遍

2023-05-04 08:34 UTC, huhuhang requested changes

2023-05-04 08:34 UTC, huhuhang commented on opencv/lab-getting-started-with-videos/step1.md
> +In this example, we create a `VideoCapture` object by passing the path to the video file we want to read. We then use a `while` loop to read each frame of the video using the `read()` method. If the
建议在这段之后，补充一个执行和预览的段落。

You can run the following command in the terminal to execute.

```bash
python /home/labex/project/read_video.py
```

Afterward, you can see the picture of each frame in the `frame` folder.

类似于这种，使得整个 lab 的跟随学习过程更自然。

2023-05-04 08:34 UTC, huhuhang commented on opencv/lab-getting-started-with-videos/step1.md
> +File path is `/home/labex/project/read_video.py`
已经 Open the `read_video.py`，然后又 File path is `/home/labex/project/read_video.py` 是不是有点重复了。

2023-05-04 08:34 UTC, huhuhang commented on opencv/lab-getting-started-with-videos/step2.md
> +File path is `/home/labex/project/write_video.py`
同理

2023-05-04 08:34 UTC, huhuhang commented on opencv/lab-getting-started-with-videos/step2.md
> +We then use a `while` loop to read each frame of the video using the `read()` method. If the frame is successfully read, we process it (e.g., apply filters) and write it to the output video using the
用户怎么看最终的视频呢？如果环境不支持预览，是不是需要下载到本地查看呢？是不是可以补充一下操作截图呢？

要代入用户视角，如果你是来学习这个 lab 的同学，学到最后连最终效果都看不到，你会如何感想？

2023-05-04 08:34 UTC, huhuhang commented on opencv/lab-getting-started-with-videos/verify2.sh
> +cat /home/labex/project/write_video.py | grep -Ez "write.+release"
是不是检测结果比检测代码更合适？比如检查最后的 `output.avi` 是否存在。

检查代码太死板，且意义不大。

2023-05-04 08:34 UTC, huhuhang commented on opencv/lab-getting-started-with-videos/verify1.sh
> +cat /home/labex/project/read_video.py | grep  "imwrite"
同理

2023-05-05 01:32 UTC, huhuhang approved these changes

2023-05-05 01:32 UTC, merged