Add challenge-basic-tqdm-usage
labex-labs/scenarios pull request #631
Opened 2023-04-27 09:57 UTC by AsukaLove2

# PR Checklist

- fix #618 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-27 11:37 UTC, AsukaLove2 commented
@GodsDusk 老师，这个测试脚本我怎么都过不了，我先将它分开在我的环境里实验了很多次，测试脚本如下图
![image](https://user-images.githubusercontent.com/105929020/234850108-958db71d-cb64-4aca-a5bb-3e4a0ea6d817.png)
它总是报错Expected 'tqdm' to be called once. Called 0 times. 我尝试改patch（）里面的内容，很多方法都试了，实在是没办法了。你有没有什么思路解决这个问题呢？

2023-04-27 11:39 UTC, AsukaLove2 commented
> @GodsDusk 老师，这个测试脚本我怎么都过不了，我先将它分开在我的环境里实验了很多次，测试脚本如下图 ![image](https://user-images.githubusercontent.com/105929020/234850108-958db71d-cb64-4aca-a5bb-3e4a0ea6d817.png)
我用的solution的代码测试， 它总是报错Expected 'tqdm' to be called once. Called 0 times. 我尝试改patch（）里面的内容，很多方法都试了，实在是没办法了。你有没有什么思路解决这个问题呢？

2023-04-27 13:57 UTC, GodsDusk commented
改用另外一个issue里的检测输出的方式把 https://github.com/labex-labs/scenarios/issues/615#issuecomment-1522675958

不过 `sys.stdout` 要改为 `sys.stderr`

2023-04-28 01:06 UTC, GodsDusk requested changes

2023-04-28 01:06 UTC, GodsDusk commented on python/challenge-basic-tqdm-usage/step1.md
> +pip install tqdm
在setup里替用户安装，同时要指定版本号避免后续有问题

2023-04-28 01:06 UTC, GodsDusk commented on python/challenge-basic-tqdm-usage/step1.md
> +Below is the source code that does not use tqdm library, you can try to add tqdm by yourself, we will not force you to complete this part.
直接把下面这段代码放 function_runner 里就行，不然多此一举了， 同下

2023-04-28 01:06 UTC, GodsDusk commented on python/challenge-basic-tqdm-usage/step1.md
> +def function_runner(lst: List[Callable]):
`-> None`

2023-04-28 01:06 UTC, GodsDusk commented on python/challenge-basic-tqdm-usage/step1.md
> +function_runner([func1, func2])
把输出也给用户显示出来，同下

2023-04-28 01:06 UTC, GodsDusk commented on python/challenge-basic-tqdm-usage/step2.md
> +        len(sub_lst)
用`pass` 就行

2023-04-28 01:06 UTC, GodsDusk commented on python/challenge-basic-tqdm-usage/assets/list_length_updater_test.py
> +        self.assertIn("100%", output)
光这个不够啊，还得判断是 5/5 而不是 2/2

2023-05-05 09:15 UTC, GodsDusk requested changes

2023-05-05 09:15 UTC, GodsDusk commented on python/challenge-basic-tqdm-usage/assets/function_runner.py
> +   # TODO
\# TODO 前面才3个空格？ 格式规范再检查一下

2023-05-05 09:15 UTC, GodsDusk commented on python/challenge-basic-tqdm-usage/assets/list_length_updater_test.py
> +        lst=[[1,2,3],[4,5]]
测试用例不要和example一样

2023-05-05 13:15 UTC, GodsDusk requested changes

2023-05-05 13:15 UTC, GodsDusk commented on python/challenge-basic-tqdm-usage/assets/function_runner.py
> +from tqdm import tqdm, trange
tqdm 不需要给用户import

2023-05-05 13:15 UTC, GodsDusk commented on python/challenge-basic-tqdm-usage/assets/function_runner.py
> +"""
直接放就行了，不用加注释，整个文件这样就行：

```python
from typing import List, Callable


def function_runner(lst: List[Callable]) -> None:
    """
    Runs a list of functions and displays a progress bar using tqdm.
    Args:
    lst (List[Callable]): A list of callable functions to be executed.
    Returns:
    None
    """
    # TODO
    for func in lst:
        func()


```

2023-05-05 13:15 UTC, GodsDusk commented on python/challenge-basic-tqdm-usage/assets/list_length_updater_test.py
> +        lst=[[1,2],[3,4,5]]
改的也太轻微了，好歹 `[[1, 2], [3, 4], [5, 6, 7, 8, 9]]` 吧

2023-05-06 01:22 UTC, GodsDusk approved these changes

2023-05-06 04:21 UTC, huhuhang requested changes

2023-05-06 04:21 UTC, huhuhang commented on python/challenge-basic-tqdm-usage/step1.md
如果给用户的基础代码块，不包含函数的调用，用户怎样执行后会显示 Example 的 Output 呢？需要用户自己补充？意义不大吧。

![CleanShot 2023-05-06 at 12 19 26](https://user-images.githubusercontent.com/5147530/236599451-e9125378-6deb-4c29-8268-68668f643292.png)

要站在用户视角来思考问题，制作内容。

2023-05-08 01:49 UTC, huhuhang requested changes

2023-05-08 01:49 UTC, huhuhang commented on python/challenge-basic-tqdm-usage/solutions/step1-solution.md
![CleanShot 2023-05-08 at 09 48 02](https://user-images.githubusercontent.com/5147530/236716369-1859123c-ce40-442a-9fac-6a44b358a8e9.png)

内容的一致性，你的 solution，一定是在预留给用户的代码上补全的，两个地方是一致的。也就是说一键复制粘贴 solution 就可以。方便我们未来给用户提供更多易用的功能。

2023-05-10 00:18 UTC, huhuhang approved these changes

2023-05-10 00:18 UTC, merged

2023-05-10 00:19 UTC, huhuhang commented
@AsukaLove2 做事情要细心，这么简单的 challenge 改了这么多遍，实在不应该。后续仔细检查确认，争取无需修改，这样效率是最高的。