challenge-file-system-operations-with-os-module
labex-labs/scenarios pull request #640
Opened 2023-04-28 10:20 UTC by xiaoshengyunan

# PR Checklist

- fix #616

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-04-29 09:45 UTC, xiaoshengyunan commented
test completed

2023-05-04 06:09 UTC, GodsDusk requested changes
以用户体验的角度考虑，不必把issue中所有的内容都搬过来，能精简的就精简

2023-05-04 06:09 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +3. Display the percentage of total disk space used by the specified directory.
从用户的角度来说，3的内容其实很让人困惑的，如何display？ print 还是 return，从你的solution中才知道是 print，这种尽量避免。用户应该一看 todo 就应该知道自己要做什么

2023-05-04 06:09 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step2.md
> +4. Provide the user with the option to delete the duplicate files.
这个就更严重了，从你的solution中看你还需要用户执行 `input` 才能完成整个 todo，但从检测脚本来看又没有这个必要。

2023-05-04 06:09 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/solutions/duplicate_file_finder.py
> +                    file_hash = hashlib.md5(file_content).hexdigest()
md5 其实没啥必要，直接文件内容作为 key 就行

2023-05-04 06:09 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/solutions/duplicate_file_finder.py
> +                        file_hash_map[file_hash] = []
这个多此一举了，明明已经定义了 defaultdict(list)，就根本没必要做 key 检测

2023-05-06 06:49 UTC, GodsDusk requested changes

2023-05-06 06:49 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/.vscode/settings.json
> +{
这个也是多余的文件吧？

2023-05-06 06:49 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +3. Print the percentage of total disk space used by the specified directory.
给个example，比如有个目录，结构如下：
```bash
.
├── 1.txt 1KB
├── 2.txt 2KB
├── 3.py 1KB
```
然后执行 `disk_space_analyzer.py` 的结果是什么？

2023-05-06 06:49 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +1. Complete `/home/labex/project/disk_space_analyzer.py` and implement a disk space analyzer using the `os` module.
Complete `get_directory_size_and_disk_usage` in `duplicate_file_finder.py`...

2023-05-06 06:49 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/solutions/disk_space_analyzer.py
> +if __name__ == "__main__":
你这部分就可以放在正文里，让用户知道执行后是什么样的

2023-05-06 12:58 UTC, GodsDusk requested changes

2023-05-06 12:58 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +1. Complete `get_directory_size_and_disk_usage` function in the file `/home/labex/project/disk_space_analyzer.py` and implement a disk space analyzer using the `os` module.
连词不对吧，语法也有问题，用 https://www.deepl.com/write 对比一下所有正文

2023-05-06 12:58 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +Take `get_directory_size_and_disk_usage("/tmp/test_directory")` as an example.
/tmp 是测试用的目录，不要给用户看，另外准备一份放当前路径，测试文件和样例文件最好不要一样

2023-05-06 12:58 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +- Assume that the block size of the file system where this directory is located is 4KB.
为啥要 assume，实际执行多少就是多少

2023-05-07 04:10 UTC, GodsDusk requested changes
理解有误，不需要给这些 *_example.py 文件，而是在 setup.sh 里执行创建文件的脚本，然后用户可以在默认目录下看到一些文件，如果用户功能正确了，那就可以通过默认目录下的文件得到与你正文中说明的相同的结果

2023-05-07 04:10 UTC, GodsDusk requested changes
理解有误，不需要给这些 *_example.py 文件，而是在 setup.sh 里执行创建文件的脚本，然后用户可以在默认目录下看到一些文件，如果用户功能正确了，那就可以通过默认目录下的文件得到与你正文中说明的相同的结果

2023-05-07 07:35 UTC, GodsDusk requested changes

2023-05-07 07:35 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +- The path of the directory is "test_example/disk_space_analyzer_example".
Take `get_directory_size_and_disk_usage("test_example/disk_space_analyzer_example")` as an example.

- The path of the directory is "test_example/disk_space_analyzer_example".

这两句可以不用

2023-05-07 07:35 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +- There are files in the path "test_example/disk_space_analyzer_example": 1.txt 1KB, 2.txt 2KB, 3.txt 3KB.
改为：

There are some files in the path "test_example/disk_space_analyzer_example": 
- 1.txt 1KB, 
- 2.txt 2KB, 
- 3.txt 3KB.

2023-05-07 07:35 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +test = get_directory_size_and_disk_usage("test_example/disk_space_analyzer_example")
改为：

```bash
python disk_space_analyzer.py 
```

2023-05-07 07:35 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/assets/disk_space_analyzer.py
> +
这里的不用让用户实现，把solution里的贴进来就行，然后用户一执行这个脚本，就知道自己要做什么了，其实考察的内容只是函数里的实现

2023-05-07 10:42 UTC, GodsDusk requested changes

2023-05-07 10:42 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/assets/batch_file_renamer.py
> +    directory_to_rename = "/path/to/rename"
写实际路径，当用户完成函数内容后，执行这个脚本应该直接就能看到结果

2023-05-07 10:42 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +3. Print the percentage of total disk space used by the specified directory.
print 不需要用户来做，去掉

2023-05-07 10:42 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +Disk usage: 0.00%
这也太小了，用 `truncate -s 200M test.file` 之类的创建，不能 0.00%

2023-05-07 10:42 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/step1.md
> +```python
前面加点过度句， when you completed, execute the script... 之类的

2023-05-08 06:11 UTC, GodsDusk requested changes

2023-05-08 06:11 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/solutions/file_extension_statistics.py
> +    for extension, count in extension_statistics.most_common():
上面 hint 返回是 `Dict[str, int]`, 这边演示怎么能用 `Counter` 的 `most_common` 方法呢，要统一

2023-05-08 06:11 UTC, GodsDusk commented on python/challenge-file-system-operations-with-os-module/solutions/duplicate_file_finder.py
> +from collections import defaultdict
只要在 solution 中用到，就要包含在 index.json 的 skill 中

2023-05-08 09:07 UTC, GodsDusk approved these changes

2023-05-10 00:29 UTC, huhuhang requested changes
看看其他步骤有没有类似的问题。

2023-05-10 00:29 UTC, huhuhang commented on python/challenge-file-system-operations-with-os-module/assets/disk_space_analyzer_test.py
![CleanShot 2023-05-10 at 08 26 45](https://github.com/labex-labs/scenarios/assets/5147530/d738ce11-db54-4d21-93fd-59d483e93ad0)

检测脚本似乎还是有点问题，例如你把答案中的 * 100，改成 200 也能过。

![CleanShot 2023-05-10 at 08 28 42](https://github.com/labex-labs/scenarios/assets/5147530/8f814cc1-104b-4337-bbff-b1fabbd3bcb6)

2023-05-11 01:01 UTC, huhuhang requested changes

2023-05-11 01:01 UTC, huhuhang commented on python/challenge-file-system-operations-with-os-module/assets/file_extension_statistics.py
> +    # Note: Do not change the existing code
TODO 是不是放错了地方？？

2023-05-11 01:01 UTC, huhuhang commented on python/challenge-file-system-operations-with-os-module/assets/file_extension_statistics.py
> +    # Note: Do not change the existing code
放在需要用户补充代码的地方。

2023-05-11 01:01 UTC, huhuhang commented on python/challenge-file-system-operations-with-os-module/assets/file_extension_statistics.py
> +    # Note: Do not change the existing code
相似问题一并检查

2023-05-11 01:47 UTC, huhuhang approved these changes

2023-05-11 01:47 UTC, merged