Add challenge docker network with compose
labex-labs/scenarios pull request #646
Opened 2023-05-03 14:07 UTC by GuoJiang-yw

# PR Checklist

- fix #604 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-05-03 14:37 UTC, GuoJiang-yw commented
Test Completed

2023-05-03 14:46 UTC, huhuhang commented
Hi, @huhuhang 

系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。

[❓ 如何 Review](https://www.labex.wiki/zh/advanced/how-to-review) | [✍️ LabEx 手册](https://www.labex.wiki/zh/advanced/how-to-review) | [🏪 LabEx 网站](https://labex.io) 

> 这是一条自动消息，如有疑问可以直接回复本条评论，或者微信联系。

2023-05-04 01:06 UTC, huhuhang requested changes
步骤 1，2，3 有相似问题，只批注一次。

2023-05-04 01:06 UTC, huhuhang commented on docker/challenge-docker-network-with-compose/step1.md
> +You will need to have Docker installed on your machine.
这个我们应该预装了，所有这句话其实是多余的。

2023-05-04 01:06 UTC, huhuhang commented on docker/challenge-docker-network-with-compose/step1.md
> +- Verify that the containers can communicate with each other by pinging one from the other.
可以把这个无序列表放在 Requirements，其实有点像要求的详细说明。而 Example 可以放一个截图，也就是最终成功后的环境终端截图，方便用户自行比对验证。

2023-05-04 01:06 UTC, huhuhang commented on docker/challenge-docker-network-with-compose/solutions/step1-solution.md
> +```
代码块一定要是复制友好型的，把需要这些多余的去掉。代码块需要加语法标识，比如这里是 bash

2023-05-04 01:06 UTC, huhuhang commented on docker/challenge-docker-network-with-compose/step1.md
> +- Verify that the containers can communicate with each other by pinging one from the other.
类似：

![CleanShot 2023-05-04 at 09 05 37](https://user-images.githubusercontent.com/5147530/236084134-17f95444-1ee3-4bfe-9fbb-0b55696b4a11.png)

2023-05-06 03:02 UTC, huhuhang approved these changes

2023-05-06 03:02 UTC, huhuhang approved these changes

2023-05-06 03:02 UTC, merged