add challenge-real-time-data-processing-system
labex-labs/scenarios pull request #651
Opened 2023-05-04 12:48 UTC by Liang-jonas

# PR Checklist

- fix #625 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-05-04 19:10 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

[❓ 如何 Review](https://www.labex.wiki/zh/advanced/how-to-review) | [✍️ LabEx 手册](https://www.labex.wiki/zh/advanced/how-to-review) | [🏪 LabEx 网站](https://labex.io) 

> 这是一条自动消息，如有疑问可以直接回复本条评论，或者微信联系。

2023-05-05 01:34 UTC, GodsDusk requested changes

2023-05-05 01:34 UTC, GodsDusk commented on python/challenge-real-time-data-processing-system/solutions/data_generator.py
> +        price = round(random.uniform(50, 200), 2)
这里为什么是 50-200？

2023-05-05 01:34 UTC, GodsDusk commented on python/challenge-real-time-data-processing-system/step1.md
> +- Use a thread-safe data structure to store the generated price updates.
已经用 queue 作为入参保证线程安全了吧，这个就不算是 todo 了，反而是简要描述一下 queue 要存储的内容（包括从 queue 拿出的内容是什么

2023-05-05 01:34 UTC, GodsDusk commented on python/challenge-real-time-data-processing-system/solutions/data_generator.py
> +        output_queue.put((symbol, price))
step1 中也没说要用 `(symbol, price)` 的形式放到 queue 中

2023-05-05 01:34 UTC, GodsDusk commented on python/challenge-real-time-data-processing-system/step2.md
> +- Use Python's multiprocessing module to run the data processor in a separate process.
`multiprocessing`

2023-05-05 01:34 UTC, GodsDusk commented on python/challenge-real-time-data-processing-system/solutions/main_function.py
> +    main()
这个答案是不是有问题，根据我的理解，执行后应该会持续打印吧，但实际执行只打印了一次

2023-05-05 08:40 UTC, Liang-jonas commented on python/challenge-real-time-data-processing-system/solutions/data_generator.py
> +        price = round(random.uniform(50, 200), 2)
> 这里为什么是 50-200？

股价嘛，随机值在50到200之间好像也没啥问题

2023-05-05 08:53 UTC, GodsDusk commented on python/challenge-real-time-data-processing-system/solutions/data_generator.py
> +        price = round(random.uniform(50, 200), 2)
> > 这里为什么是 50-200？
> 
> 股价嘛，随机值在50到200之间好像也没啥问题

用户不知道啊，正文中提一下 。。

2023-05-06 01:35 UTC, GodsDusk requested changes

2023-05-06 01:35 UTC, GodsDusk commented on python/challenge-real-time-data-processing-system/solutions/main_function.py
> +sys.path.append("/home/labex/project")
这个多余了

2023-05-06 01:35 UTC, GodsDusk commented on python/challenge-real-time-data-processing-system/index.json
> +  "description": "In this challenge, you will use Python's threading and multi-processing capabilities to create a program to simulate a real-time stock market data processing system.",
还是太长了

2023-05-06 01:35 UTC, GodsDusk commented on python/challenge-real-time-data-processing-system/index.json
> +        "skills": ["python/threading"],
skill 少了

2023-05-06 03:13 UTC, GodsDusk approved these changes

2023-05-06 05:10 UTC, huhuhang requested changes

2023-05-06 05:10 UTC, huhuhang commented on python/challenge-real-time-data-processing-system/step1.md
没有 Example，示例一下输入和返回，我感觉完全摸不着头脑啊。

2023-05-08 01:44 UTC, huhuhang approved these changes

2023-05-08 01:45 UTC, merged