finish the regular-expressions-mastery challenge
labex-labs/scenarios pull request #663
Opened 2023-05-06 14:22 UTC by anonym10048

# PR Checklist

- fix #620

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-05-06 15:09 UTC, anonym10048 commented
task completed

2023-05-07 05:08 UTC, GodsDusk requested changes

2023-05-07 05:08 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step1.md
> +2. Use regex to extract the following information from each log entry:<br>
多余的 \<br>

2023-05-07 05:08 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step1.md
> +   e. Top user agents<br>
给一些输入输出的example

2023-05-07 05:08 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step1.md
> +## Requirements
在哪实现？

2023-05-07 05:08 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step1.md
> +3. Store the extracted information in a structured format (e.g., a list of dictionaries or a pandas DataFrame).
结合solution来看，需要做这一步吗？

2023-05-07 05:27 UTC, anonym10048 commented on python/challenge-regular-expressions-mastery/step1.md
> +2. Use regex to extract the following information from each log entry:<br>
不要这个<br>的话后面的a.IP address不是会和前面的连在一起吗

2023-05-07 06:36 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step1.md
> +2. Use regex to extract the following information from each log entry:<br>
> 不要这个的话后面的a.IP address不是会和前面的连在一起吗

![屏幕截图 2023-05-07 143413](https://user-images.githubusercontent.com/13726533/236661867-f512a2be-b6b1-4f14-9c47-42a1f6a7c706.png)

我本地看了并不会，如果线上渲染有问题的话群里说下，让开发去改

2023-05-07 07:58 UTC, GodsDusk requested changes

2023-05-07 07:58 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step1.md
> +Suppose we have a `sample_log.txt` file like this:
不要 Suppose，通过setup.sh，直接在默认目录里给出

2023-05-07 07:58 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step1.md
> +### Example
怎么有两个 example？ 应该放在一起说

2023-05-07 07:58 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step1.md
> +print(parse_log_file(sample_log.txt))
给的 example 应该是让用户执行 `python web_log_analysis.py ` ，然后脚本会输出期望内容

2023-05-07 07:58 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step1.md
> +print(parse_log_file(sample_log.txt))
而且你这语法也有问题，字符串没"",执行就报错了

2023-05-07 07:58 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/assets/web_log_analysis.py
> +
```python
if __name__ == '__main__':
    step1 = parse_log_file('sample_log.txt')
    print(f'{step1=}')
    step2 = analyze_log_entries(step1)
    print(f'{step2=}')
```

这样让用户去执行，不就可以很清楚的知道这个challenge是要做什么了

2023-05-07 07:58 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/assets/web_log_analysis.py
> +
多余的换行，用格式化工具都格式一遍

2023-05-08 10:55 UTC, anonym10048 commented on python/challenge-regular-expressions-mastery/step1.md
> +Suppose we have a `sample_log.txt` file like this:
是通过setup.sh在当前路径创建一个txt文件对吗，用assest上传可以吗

2023-05-08 12:55 UTC, GodsDusk requested changes

2023-05-08 12:55 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/solutions/web_log_analysis.py
> +    }
要和用户看到的文件一致，缺了 __main__

2023-05-08 12:55 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/solutions/web_log_analysis.py
> +    }
而且我用给的代码提交，也没法通过检测

2023-05-09 01:39 UTC, GodsDusk requested changes

2023-05-09 01:39 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step3.md
> +```python
这个就不用给这么多样例了，1，2个就行

2023-05-09 01:39 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step3.md
> +   c. Does not contain any forbidden patterns (e.g., "123", "password", "qwerty", etc.)<br>
检测里没要求，而且eg...etc会让用户困扰，到底要实现个什么，那还不如把这句去了

2023-05-09 01:39 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step1.md
> +3. Complete the `analyze_log_entries` function in `web_log_analysis.py`, which stores the extracted information in a structured format (e.g. a list of dictionaries or a pandas DataFrame).
e.g. 这种说明，全篇还是不要出现了，挑战内容得明确，不要引起用户的困扰

2023-05-09 01:39 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/assets/extracting_information_test.py
> +        sample_config = '''
检测用例不要和给用户展示的一样

2023-05-09 01:39 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/assets/extracting_information_test.py
> +        sample_config = '''
下同

2023-05-10 10:21 UTC, GodsDusk requested changes

2023-05-10 10:21 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/solutions/password_validator.py
> +    print(is_password_valid(password_2))
你这solution没法pass了

2023-05-10 10:21 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/index.json
> +    "description": "In this challenge, you will master the use of regular expressions (regex) in Python by completing a series of complex sub-challenges.",
太长了，而且不要照抄intro

2023-05-10 11:31 UTC, anonym10048 commented on python/challenge-regular-expressions-mastery/solutions/web_log_analysis.py
> +from collections import Counter
我之前是写了的 然后系统没给我过

2023-05-11 01:05 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/solutions/web_log_analysis.py
> +from collections import Counter
> 我之前是写了的 然后系统没给我过

什么报错？ 群里问下开发

2023-05-11 12:51 UTC, anonym10048 commented
求reviewT T不知道为什么点不了那个按钮

2023-05-11 13:38 UTC, anonym10048 commented
@GodsDusk

2023-05-12 01:27 UTC, GodsDusk requested changes

2023-05-12 01:27 UTC, GodsDusk commented on python/challenge-regular-expressions-mastery/step3.md
> +2. Use regex to check if the password meets the following criteria:<br>
这边的 \<br> 没去掉，整个项目全局查找一下

2023-05-12 01:46 UTC, anonym10048 commented
@GodsDusk

2023-05-12 02:38 UTC, GodsDusk approved these changes

2023-05-13 02:08 UTC, huhuhang requested changes
相似问题一并处理。

2023-05-13 02:08 UTC, huhuhang commented on python/challenge-regular-expressions-mastery/step1.md
> +# Web log analysis
Title Case

2023-05-13 02:08 UTC, huhuhang commented on python/challenge-regular-expressions-mastery/step2.md
> +3. Replace the '@' symbol with ' [at] ' and the '.' symbol with ' [dot] ' in the email addresses.
代码关键字，用行内代码样式。

2023-05-16 01:17 UTC, merged