add Challenge docker search command
labex-labs/scenarios pull request #669
Opened 2023-05-07 12:29 UTC by Liang-jonas

# PR Checklist

- fix #650 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-05-07 19:10 UTC, huhuhang commented
Hi, @joker-bai 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

[❓ 如何 Review](https://www.labex.wiki/zh/advanced/how-to-review) | [✍️ LabEx 手册](https://www.labex.wiki/zh/advanced/how-to-review) | [🏪 LabEx 网站](https://labex.io) 

> 这是一条自动消息，如有疑问可以直接回复本条评论，或者微信联系。

2023-05-08 01:25 UTC, joker-bai requested changes

2023-05-08 01:25 UTC, joker-bai commented on docker/challenge-docker-search-command/step1.md
> +![search-alpine-image](assets/search-alpine-image.png)
图片请按规范进行命名https://labex-docs.vercel.app/zh/basic/formatting-guide#%E5%9B%BE%E7%89%87

2023-05-08 01:25 UTC, joker-bai commented on docker/challenge-docker-search-command/step1.md
> +``` zsh
这里不需要给出具体的命令，challenge就是要用户自己去思考命令。下同。

2023-05-08 01:25 UTC, joker-bai commented on docker/challenge-docker-search-command/step1.md
> +2. Search for the `alpine` image on the Docker Hub registry.
这里的镜像如果改成了nginx，包括下面的图片，截图只截结果，不截命令就行

2023-05-08 01:25 UTC, joker-bai commented on docker/challenge-docker-search-command/step2.md
> +$ docker search --filter "is-official=true" alpine
这里一样不需要命令提示

2023-05-08 01:25 UTC, joker-bai commented on docker/challenge-docker-search-command/step2.md
> +![filtering-search-results](assets/filtering-search-results.png)
图片格式需要修改。

2023-05-08 01:25 UTC, joker-bai commented on docker/challenge-docker-search-command/step1.md
> +## Example
标题统一改成 Result Example 吧

2023-05-08 01:25 UTC, joker-bai commented on docker/challenge-docker-search-command/step3.md
> +$ docker search --format "table {{.Name}}\t{{.Description}}\t{{.StarCount}}" alpine
这里一样不需要命令

2023-05-08 01:25 UTC, joker-bai commented on docker/challenge-docker-search-command/step3.md
> +![displaying-more-information](assets/displaying-more-information.png)
图片格式问题

2023-05-08 01:25 UTC, joker-bai commented on docker/challenge-docker-search-command/step4.md
> +$ docker search --format "table {{.Name}}\t{{.Description}}\t{{.StarCount}}" --limit 5 alpine
不需要命令

2023-05-08 01:25 UTC, joker-bai commented on docker/challenge-docker-search-command/step4.md
> +![show-max-number](assets/show-max-number.png)
图片格式问题

2023-05-08 03:42 UTC, Liang-jonas commented on docker/challenge-docker-search-command/step1.md
> +``` zsh
> 这里不需要给出具体的命令，challenge就是要用户自己去思考命令。下同。

之前我做的挑战里面，都是说把命令贴出来方便挑战者复制呀，这回的不需要了嘛

2023-05-10 00:05 UTC, huhuhang commented on docker/challenge-docker-search-command/step1.md
> +2. Search for the `alpine` image on the Docker Hub registry.
@Liang-jonas 这里应该还是有问题吧，图片里有操作命令，用户还 challenge 干啥？

2023-05-10 00:05 UTC, huhuhang commented on docker/challenge-docker-search-command/step1.md
> +2. Search for the `alpine` image on the Docker Hub registry.
![CleanShot 2023-05-10 at 08 05 18](https://github.com/labex-labs/scenarios/assets/5147530/3873b02d-aa12-4f0e-b4fe-6ad22aaa3958)

2023-05-10 00:09 UTC, huhuhang requested changes
对 challenge 的理解不到位，抽空看一下这几个 PR：

https://github.com/labex-labs/scenarios/pull/675
https://github.com/labex-labs/scenarios/pull/673
https://github.com/labex-labs/scenarios/pull/672
https://github.com/labex-labs/scenarios/pull/671

2023-05-11 01:09 UTC, huhuhang requested changes

2023-05-11 01:09 UTC, huhuhang commented on docker/challenge-docker-search-command/step1.md
> +- Docker should be installed on your system.
这个是不是可以去掉，Docker 在环境中肯定是存在的，另外，每个 step 都重复这句话，感觉除了冗长，没有意义。

2023-05-13 02:14 UTC, huhuhang approved these changes

2023-05-13 02:14 UTC, huhuhang approved these changes

2023-05-13 02:14 UTC, huhuhang approved these changes

2023-05-13 02:14 UTC, huhuhang approved these changes

2023-05-13 02:16 UTC, merged