add challenge-dataframe-combiner
labex-labs/scenarios pull request #694
Opened 2023-05-10 18:23 UTC by Liang-jonas

# PR Checklist

- fix #678 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-05-11 01:16 UTC, GodsDusk requested changes

2023-05-11 01:16 UTC, GodsDusk commented on pandas/challenge-dataframe-combiner/assets/create_dataframe_test.py
> +from create_dataframe import create_dataframe
这些 test 用 __main__ 的方式放对应文件里就行了吧

2023-05-11 01:16 UTC, GodsDusk commented on pandas/challenge-dataframe-combiner/step1.md
> +    E   X   A   M   P   L   E
每一行都要注释符 #，不然直接复制黏贴就报错了

2023-05-11 01:16 UTC, GodsDusk commented on pandas/challenge-dataframe-combiner/assets/create_dataframe_system_test.py
> +        self.assertEqual(df.shape, (rows, len(columns)))
再加个调用两次，判断返回的df不相同来test用户真的用了random吧

2023-05-11 02:02 UTC, huhuhang commented
Hi, @GodsDusk 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

[❓ 如何 Review](https://www.labex.wiki/zh/advanced/how-to-review) | [✍️ LabEx 手册](https://www.labex.wiki/zh/advanced/how-to-review) | [🏪 LabEx 网站](https://labex.io) 

> 这是一条自动消息，如有疑问可以直接回复本条评论，或者微信联系。

2023-05-12 01:12 UTC, GodsDusk requested changes

2023-05-12 01:12 UTC, GodsDusk commented on pandas/challenge-dataframe-combiner/assets/concatenating_dataframes_test.py
> +      self.assertTrue(set(df_concat.columns) == {'A', 'B', 'C'})
用 mock.patch 保证用户调用了 `create_dataframe`，而不是直接生成一个对应shape的df就返回了
concat 方法就不检测了，万一用户新建了一个空df，然后遍历赋值

2023-05-14 02:33 UTC, GodsDusk approved these changes

2023-05-16 00:53 UTC, huhuhang requested changes

2023-05-16 00:53 UTC, huhuhang commented on pandas/challenge-dataframe-combiner/intro.md
> +# Dataframe Combiner
DataFrame

搜索检查一下类似问题。

2023-05-16 00:53 UTC, huhuhang commented on pandas/challenge-dataframe-combiner/intro.md
> +In this challenge, we will explore the different ways to combine `Pandas` DataFrames. You'll practice merging, concatenating, and joining DataFrames using various techniques to obtain the desired out
行内代码样式不要乱用。仅用于：代码、路径、文件名

2023-05-16 02:13 UTC, huhuhang commented on pandas/challenge-dataframe-combiner/intro.md
> +# Dataframe Combiner
还有 challenge title 里面

2023-05-17 00:50 UTC, huhuhang approved these changes

2023-05-17 00:50 UTC, merged