add challenge-examine-nodes-with-kubectl
labex-labs/scenarios pull request #763
Opened 2023-05-16 15:09 UTC by Liang-jonas

# PR Checklist

- fix #667 

请替换上方 `ID` 为本 PR 相关的 Issue ID，如 `fix #18`。Issue ID 可以在 Issue 的 URL 中找到，如 `https://github.com/labex-labs/scenarios/issues/18`，则 ID 为 `18`。

请保留上方链接前的 `fix ` 关键字，确保 issue 可以在 PR 合并后自动关闭。

你的内容会被自动同步上线并生成测试课程，完成 [线上测试](https://www.labex.wiki/zh/basic/how-to-test) 后，请评论 "test completed"，以便我们知道你已完成测试。

感谢你提出 PR，为 LabEx 做出贡献！

---

Please replace `ID` with the relevant Issue ID for this PR, such as `fix #18`. The Issue ID can be found in the URL of the Issue, for example, `https://github.com/labex-labs/scenarios/issues/18`, where the ID is `18`.

Please keep the `fix ` keyword before the link to ensure the issue is automatically closed after the PR is merged.

Your content will be automatically synchronized online and a test course will be generated. After completing the [online test](https://www.labex.wiki/en/basic/how-to-test), please comment "test completed" so that we know you have finished the test.

Thank you for submitting a PR and contributing to LabEx!

2023-05-16 19:10 UTC, huhuhang commented
Hi, @joker-bai 

由于该 PR 关联了由你创建的 Issue，系统已将你自动分配为 Reviewer，请你及时完成 Review，并和作者进行沟通。确认无误后，可以执行 `Approve` 操作，LabEx 会二次确认后再合并。请勿自行合并 PR。

[❓ 如何 Review](https://www.labex.wiki/zh/advanced/how-to-review) | [✍️ LabEx 手册](https://www.labex.wiki/zh/advanced/how-to-review) | [🏪 LabEx 网站](https://labex.io) 

> 这是一条自动消息，如有疑问可以直接回复本条评论，或者微信联系。

2023-05-18 02:33 UTC, joker-bai requested changes
对于图片，是给用户呈现结果的，而不是展示命令的执行结果，单纯的执行结果意义不大。有的步骤如果实在给不出图片，也可以不需要图片，在检测步骤检测即可。

2023-05-18 02:33 UTC, joker-bai commented on kubernetes/challenge-examine-nodes-with-kubectl/verify1-1.sh
> +cat /home/labex/.zsh_history | grep "kubectl get nodes"
检测命令要考虑用户输入空格的情况，比如如果用户输入`kubectl      get       nodes` 依然能够得到node的信息，但是这个检测脚本就不会通过，另外还需要考虑简写的问题，比如`kubectl get node` 也能得到用户信息

2023-05-18 02:33 UTC, joker-bai commented on kubernetes/challenge-examine-nodes-with-kubectl/step2.md
> +![challenge-examine-nodes-with-kubectl-2-2](assets/challenge-examine-nodes-with-kubectl-2-2.png)
![image](https://github.com/labex-labs/scenarios/assets/34888500/f5de25c2-bcaf-4197-b292-2a4d8adbbe96)
这里的图片像这样更好，可以给用户更直观的看到这一步的最终目的是怎么样的，下面的一样。

2023-05-18 02:33 UTC, joker-bai commented on kubernetes/challenge-examine-nodes-with-kubectl/step3.md
> +![challenge-examine-nodes-with-kubectl-3-2](assets/challenge-examine-nodes-with-kubectl-3-2.png)
![image](https://github.com/labex-labs/scenarios/assets/34888500/1b587f35-ad4d-44c6-abf4-741879e82cb8)
这里的图片依然如此。

2023-05-18 02:33 UTC, joker-bai commented on kubernetes/challenge-examine-nodes-with-kubectl/step3.md
> +## Tip
这里的Tip不需要，我们Solution的作用就是如此。

2023-05-18 02:33 UTC, joker-bai commented on kubernetes/challenge-examine-nodes-with-kubectl/step3.md
> +![challenge-examine-nodes-with-kubectl-3-3](assets/challenge-examine-nodes-with-kubectl-3-3.png)
![image](https://github.com/labex-labs/scenarios/assets/34888500/78df4574-9f5d-4f74-ae08-da66e4802672)
这里截图问题相同

2023-05-18 02:33 UTC, joker-bai commented on kubernetes/challenge-examine-nodes-with-kubectl/step6.md
> +![challenge-examine-nodes-with-kubectl-6-1](assets/challenge-examine-nodes-with-kubectl-6-1.png)
![image](https://github.com/labex-labs/scenarios/assets/34888500/5e5ac6b8-c924-4c73-8abd-5e8057f5c442)
图片相同问题

2023-05-18 02:33 UTC, joker-bai commented on kubernetes/challenge-examine-nodes-with-kubectl/step6.md
> +![challenge-examine-nodes-with-kubectl-6-2](assets/challenge-examine-nodes-with-kubectl-6-2.png)
![image](https://github.com/labex-labs/scenarios/assets/34888500/ed70db9f-9e0f-417a-a586-838ddc209ab5)
问题相同

2023-05-19 16:58 UTC, Liang-jonas commented
@joker-bai 修改完成了，但是step3的第二张图换不上去，明天我问问张老师

2023-05-22 01:51 UTC, joker-bai approved these changes

2023-05-22 05:24 UTC, huhuhang approved these changes

2023-05-22 05:24 UTC, huhuhang approved these changes

2023-05-22 05:24 UTC, merged